- build.gradle
- hub/saml-soap-proxy/build.gradle
- inttest.gradle
And update gradle files to stop using methods deprecated in gradle 4.
> Bau update dependencies

- hub/config/README.md
- hub/policy/README.md
- hub/saml-proxy/README.md
> BAU: remove references to frontend-api

- build.gradle
- hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java
> ABD21: upgrade to new event emitter to enable encryption

- configuration/local/saml-engine.yml
- configuration/local/saml-proxy.yml
- configuration/local/saml-soap-proxy.yml
- hub/saml-engine/src/test/resources/saml-engine.yml
- hub/saml-proxy/src/test/resources/saml-proxy.yml
- hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
Co-Authored-by: Aditya Pahuja <aditya.pahuja@digital.cabinet-office.gov.uk>
> BAU: Update the config files to make them ready to use new config class in saml-libs

- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/Cycle3DataResourceTest.java
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasMatchingServiceResourceIntegrationTest.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/PolicyState.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateController.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle3MatchRequestSentStateController.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/StateControllerFactory.java
Added new StateController EidasCycle0And1MatchRequestSentStateController.
Updated PolicyState with existing states.
Updated StateControllerFactory to return new StateController.
Added tests for transitions from EidasCycle3MatchRequestSentState to Match and NoMatch states.
> EID-425 Added StateController and Tests

- hub/config/src/main/java/uk/gov/ida/hub/config/ConfigModule.java
- hub/config/src/main/java/uk/gov/ida/hub/config/application/MatchingServiceAdapterService.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/MatchingServiceResource.java
- hub/config/src/test/java/uk/gov/ida/hub/config/application/MatchingServiceAdapterServiceTest.java
creation of new endpoint that will return list of msa hostnames
Co-authored-by Amrit Sidhu <amrit.sidhu@digital.cabinet-office.gov.uk>
> CTV-16: Refactored msa resource in config service to allow easier

- .travis.yml
- hub/config/build.gradle
- hub/policy/build.gradle
- hub/saml-engine/build.gradle
- hub/saml-proxy/build.gradle
- hub/saml-soap-proxy/build.gradle
> bau: test on more java versions, run integration tests on travis

- build.gradle
- configuration/local/policy.yml
- configuration/local/saml-proxy.yml
- configuration/local/saml-soap-proxy.yml
- debian/policy/policy.yml
- debian/saml-proxy/saml-proxy.yml
- debian/saml-soap-proxy/saml-soap-proxy.yml
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java
- hub/policy/src/test/resources/policy.yml
- hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java
- hub/saml-proxy/src/test/resources/saml-proxy.yml
- hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java
- hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
> TRELLO-8Xm7DiDy: Reinstate previous (reverted) PR

- build.gradle
- v50 contains some more explicit/useful logging
> TRELLO-8Xm7DiDy: Upgrade event emitter

- debian/config/orch-deploy
- debian/policy/orch-deploy
- debian/saml-engine/orch-deploy
- debian/saml-proxy/orch-deploy
- debian/saml-soap-proxy/orch-deploy
These packages no longer contain anything and are no longer needed. Stop
attempting to deploy them.
> BAU: Stop trying to deploy app-config packages

- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/HealthCheckData.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthChecker.java
- hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/HealthCheckDataTest.java
See commits for further information.
> EID 866 - Move extraction logic for MSA version from request id and add extraction for eidas/sha1

- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthChecker.java
We want to be able to take more information from the MSA healthcheck response, and pass it through to the saml soap proxy endpoint to give better oversight on MSA configuration. 
To make it possible to do this, we have simplified the health check code to remove complex code branches. In particular we have reduced our reliance on the response dto as a data handling object, and are instead passing through the variables as necessary directly. This makes our method signatures more specific and readable, and better supports Functional Programming code flow that is easier to follow.
> EID-866: Refactor MSA HealthChecker to support adding eidasEnabled/shouldSignWithSha1 variables

- hub-saml/src/test/java/uk/gov/ida/saml/hub/api/HubTransformersFactoryTest.java
- Make test clearer by providing hubSigningCert when needed
> EID-939 - Change test to use X509 rather than boolean

- build.gradle
> Trello-JJU68z53: Upgrade event emitter

- README.md
- hub/config/build.gradle
- hub/policy/build.gradle
- hub/saml-engine/build.gradle
- hub/saml-proxy/build.gradle
- hub/saml-soap-proxy/build.gradle
- hub/stub-event-sink/build.gradle
- pre-commit.sh
- startup.sh
- Reference scripts from ida-hub-acceptance-tests
- Remove stuff about copyToLib since everything uses distZip now
> BAU: Remove references to VLS

- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/NoKeyConfiguredForEntityExceptionMapper.java
- hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/NoKeyConfiguredForEntityExceptionMapperTest.java
This is [tech debt](https://trello.com/c/ghzLgKUV/77-saml-proxy-should-return-json-instead-of-an-html-error-page) and also fixing [ZD#3474998](https://govuk.zendesk.com/agent/tickets/3474998). For some reason we have a special exception mapper for this exception type and it didn't return a proper `ErrorStatusDto`. We now return one.
> TRELLO-ghzLgKUV: Return JSON for `NoKeyConfiguredForEntityException`.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- hub-saml-test-utils/src/main/java/uk/gov/ida/saml/core/test/validators/SingleCertificateSignatureValidator.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/metadata/MetadataCredentialResolverInitializer.java
Update build.gradle to use build 162 of verify-saml-libs.
Adjust import in two tests to reflect new opensaml package structure.
> HUB-396 upgrade opensaml to 3.4.0

- hub/policy/src/main/java/uk/gov/ida/hub/policy/proxy/MatchingServiceConfigProxy.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/proxy/MatchingServiceConfigProxy.java
We don't need to try-catch a exception that we just re-throw.
> BAU: Clean up try-catch block that is redundant.

- build.gradle
- hub-saml-test-utils/build.gradle
- hub-saml/src/test/java/uk/gov/ida/saml/hub/api/HubTransformersFactoryTest.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/outbound/OutboundResponseFromHubToSamlResponseTransformerTest.java
- hub/policy/build.gradle
- hub/saml-engine/build.gradle
- hub/saml-proxy/build.gradle
- hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageSenderHandlerTest.java
- hub/saml-soap-proxy/build.gradle
- hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/config/ConfigServiceKeyStoreTest.java
- hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/domain/TimeoutEvaluatorTest.java
> BAU: Upgrade to the latest version of SAML libs and dev-pki

- hub/config/src/main/java/uk/gov/ida/hub/config/domain/TranslationData.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/TranslationDataBuilder.java
Co-authored-by: Alex Newton <alex.newton@digital.cabinet-office.gov.uk>
Co-authored-by: Paula Valenca <paula.valenca@digital.cabinet-office.gov.uk>
Co-authored-by: John Watts <john.watts@digital.cabinet-office.gov.uk>
> dCnwuq3t: Add special text for UC users on IDP disconnection

- README.md
- We want to be running the Hub locally in JDK11
> bau - change readme to reflect reality

- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
MSAs frequently send back 500s with no further information. Split out the exception so that Sentry reports this as separate. Should help ensure that the other exceptions don't get lost in the noise.
Also replace `'` with `''` in the format body:
> Within a String, a pair of single quotes can be used to quote any arbitrary characters except single quotes. For example, pattern string "'{0}'" represents string "{0}", not a FormatElement. A single quote itself must be represented by doubled single quotes '' throughout a String. For example, pattern string "'{''}'" is interpreted as a sequence of '{ (start of quoting and a left curly brace), '' (a single quote), and }' (a right curly brace and end of quoting), not '{' and '}' (quoted left and right curly braces): representing string "{'}", not …
> N7edPMiO: split out unhelpful MSA errors

- .travis.yml
Following the Codacy suggestions, I've got it working.
> BAU: fix Codacy coverage reporting

- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
We have a Dropwizard Metrics Timer to record times taken for
AttributeQuery requests (ie SOAP requests to matching services).
However they are somewhat fiddly to deal with in prometheus.
This creates a prometheus Summary to capture this data.  A big
advantage is that the matching service URI will be available as a
label rather than a weirdly formatted part of the metric name, so we
can more easily do queries for things like "show me the slowest 3
matching service URIs".
I picked the quantiles to be a useful subset of the current quantiles
on the dropwizard Timer.
> port AttributeQuery request Timer to prometheus

- build.gradle
- hub/config/build.gradle
- hub/policy/src/main/java/uk/gov/ida/hub/policy/configuration/EventEmitterConfiguration.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java
Reverts alphagov/verify-hub#301
> Revert "OGD-138: Integrate verify-event-emitter library updated with SQS."

- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
This adds prometheus counters to count total number of MSA requests
attempted and how many of them were successful.  We can compute error
rates from this by subtracting successful from total.
It also corrects a typo in a prometheus summary.
> Count total and successful MSA requests

- Dockerfile
* The build passed locally and in Travis, but failed in Concourse because the new library from previous commit was not included in the Dockerfile build.
Co-authored-by: James Howes <james.howes@digital.cabinet-office.gov.uk>
> OGD-169: Use :hub:shared inside Dockerfile (fix)

- hub/config/src/main/java/uk/gov/ida/hub/config/data/ManagedEntityConfigRepository.java
This shouldn't be an ERROR, WARN is sufficient.
> BAU: Turn down log level

- hub/config/src/main/java/uk/gov/ida/hub/config/ConfigApplication.java
- hub/config/src/main/java/uk/gov/ida/hub/config/S3ConfigSourceModule.java
Extract the anonymous inner class used for binding `S3ConfigSource` into
its own class, simplifying `ConfigApplication`.
> BAU: Refactor Guice Module for S3ConfigSource

- .travis.yml
- README.md
Update GitHub token used to pull Codacy coverage library from GitHub
> BAU: Fix Travis

- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/config/ConfigServiceKeyStore.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/config/TrustStoreForCertificateProvider.java
- hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/config/ConfigServiceKeyStoreTest.java
This is the saml-proxy equivalent of https://github.com/alphagov/verify-hub/pull/322
> 0BFh8hBN: RP truststore feature flag in saml-proxy

- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/ConfigServiceKeyStore.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/TrustStoreForCertificateProvider.java
- hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/config/ConfigServiceKeyStoreTest.java
This is the saml-soap-proxy equivalent of #322 and #325.
> yEeMzm3Q: RP truststore feature flag in saml-soap-proxy

- hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/AuthnRequestFromRelyingPartyUnmarshallerTest.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/outbound/EidasAuthnRequestFromHubToAuthnRequestTransformerTest.java
These tests can be expressed a bit more concisely/accurately
> Clean up a couple of tests

- hub/config/src/main/java/uk/gov/ida/hub/config/dto/CertificateHealthCheckDto.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/CertificatesResource.java
- hub/config/src/test/java/uk/gov/ida/hub/config/dto/CertificateHealthCheckDtoTest.java
Simplify `CertificatesResource`
> BAU: Simplify CertificatesResource

- hub-saml/src/main/java/uk/gov/ida/saml/core/transformers/outbound/decorators/AssertionBlobEncrypter.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/IdpIdaStatus.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/authnrequest/AuthnRequestIdKey.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/IdpIdaStatus.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/EidasMetadataResolver.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/MethodAlgorithm.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/EidasProfileValidationSpecification.java
See individual commit messages for details.
Co-Authored-By: IntelliJ linter
> A few small cleanups

- hub-saml-test-utils/src/main/java/uk/gov/ida/saml/core/test/builders/NameIdPolicyBuilder.java
- hub-saml-test-utils/src/main/java/uk/gov/ida/saml/hub/test/builders/HubAttributeQueryRequestBuilder.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/api/HubTransformersFactory.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/InboundResponseFromIdpDataGenerator.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/PassthroughAssertionUnmarshaller.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/response/idp/components/EncryptedResponseFromIdpValidator.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/builders/HubEidasAttributeQueryRequestBuilder.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/TransactionsResource.java
- hub/config/src/main/java/uk/gov/ida/hub/config/validators/IdentityProviderConfigOnboardingTransactionValidator.java
- hub/config/src/main/java/uk/gov/ida/hub/config/validators/TransactionConfigMatchingServiceValidator.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/services/CountriesService.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/AbstractContextExceptionMapper.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthChecker.java
We can improve and simplify our use of `Optional`. See individual commits for details.
Co-Authored-By: IntelliJ
> Make better use of Optional

- hub/config/src/main/java/uk/gov/ida/hub/config/data/LevelsOfAssuranceConfigValidator.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/NotOnOrAfterLogger.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/VerifiedAttributesLogger.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/EidasAttributeStatementAssertionValidator.java
There are a few places where we can make better use of the `Stream`s API and also a few places where use it but don't need to (e.g. we can do `List.forEach`)
> Make better / less use of Streams

- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyIntegrationApplication.java
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/rest/EidasCycle3DTO.java
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/rest/EidasCycle3DTOTest.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/contracts/AbstractAttributeQueryRequestDto.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/contracts/EidasAttributeQueryRequestDto.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/Cycle3AttributeRequestData.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/Cycle3Dataset.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/PersistentId.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/ResponseProcessingDetails.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/exception/StateProcessingValidationException.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasMatchRequestSentState.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/contracts/EidasAttributeQueryRequestDtoTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/Cycle3AttributeRequestDataTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/Cycle3DatasetTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/PersistentIdTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/ResponseFromHubTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/ResponseProcessingDetailsTest.java
- hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorServiceTest.java
- hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/MatchingServiceRequestSenderTest.java
- hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/client/TestResponse.java
See individual commits for details.
> Miscellaneous small code tidyups

- hub-saml/src/main/java/uk/gov/ida/saml/hub/api/HubTransformersFactory.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/IdpIdaStatus.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/TransactionsResource.java
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/MatchingServiceResourcesIntegrationTest.java
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/ConfigStubRule.java
- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/builders/InboundResponseFromIdpDtoBuilder.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/proxy/TransactionsConfigProxy.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/AttributeQueryRequestBuilder.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/domain/InboundResponseFromIdpDtoBuilder.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandlerTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/services/MatchingServiceResponseServiceTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/validators/LevelOfAssuranceValidatorTest.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/handlers/HubAsIdpMetadataHandler.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/MatchingServiceHealthCheckClient.java
We don't need to be so explicit with our types. The compiler will figure it out.
> Use type inference more

- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/config/ConfigServiceKeyStore.java
- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/config/ConfigServiceKeyStore.java
- hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/ConfigServiceKeyStore.java
`Optional` is quite powerful. Wield it appropriately.
> Simplify certificate validation

- hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/SelfServiceCertificatesResourceIntegrationTest.java
- hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateService.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/CertificateOrigin.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/CertificateValidityChecker.java
- hub/config/src/test/java/uk/gov/ida/hub/config/application/CertificateServiceTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/CertificateValidityCheckerTest.java
https://trello.com/c/BMqfOfOf/542-stop-validating-certificates-against-federation-certificate-chain-when-serving
> BMqfOfOf: Stop validating self-service certs against trust chain

- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/EnabledIdpPredicate.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactory.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/NewUserIdpPredicate.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/OnboardingForTransactionEntityPredicate.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/OnboardingIdpPredicate.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/SingleIdpEnabledPredicate.java
- hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/SupportedLoaIdpPredicate.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/EnabledIdpPredicateTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactoryPredicatesTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactoryTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/NewUserIdpPredicateTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/OnboardingForTransactionEntityPredicateTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/PredicateTestHelper.java
- hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/handlers/HubAsIdpMetadataHandlerTest.java
> Replace guava Predicates with Java ones

- hub/policy/src/main/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandler.java
Avoid an unchecked assignment by setting the variable to have a better generic type.
> BAU: Be more specific with generics

- hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/TestSessionResource.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasAwaitingCycle3DataStateController.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateController.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasAwaitingCycle3DataState.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCycle0And1MatchRequestSentState.java
- hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCycle3MatchRequestSentState.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasAwaitingCycle3DataStateBuilder.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasCycle0And1MatchRequestSentStateBuilder.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasCycle3MatchRequestSentStateBuilder.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasAwaitingCycle3DataStateControllerTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateControllerTest.java
- hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/serialization/StateJsonSerializationTest.java
Reverts alphagov/verify-hub#392
Reverting as has broken staging tests.
> Revert "Eid 1714 pass country resposne data to cycle3 attribute query"

- build.gradle
- brings in change to adjust logging for expired assertions
https://govukverify.atlassian.net/browse/EID-1755
> Bump saml-lib version

- Dockerfile
I've grepped the repo and this should be the last of them.
> BAU Upgrade other gradle base image

- build.gradle
- hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/EidasAttributesLogger.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/providers/DecoratedSamlResponseToIdaResponseIssuedByIdpTransformer.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/domain/EidasAttributesLoggerTest.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/providers/DecoratedSamlResponseToIdaResponseIssuedByIdpTransformerTest.java
- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorService.java
- hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorServiceTest.java
This reverts commit bdd65ff17244041b4f0307084b19e8b2f1507c62.
> Revert "EID-1762 Move eIDAS hash logging logic to SAML lib"

- hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateExpiryDateCheckService.java
This change updates CertificateExpiryDateCheckService to catch exception inside the loop and to provide more details on the exception and certificate if it is available. This is to ensure that CertificateExpiryDateCheckService can continue to set certificate expiry dates metrics for the remaining certificates.
This change also updates logger to log exceptions as error messages rather than warning messages so that Sentry can catch them and alert 2nd Verify Line Support team.
Co-authored by: George Lund <george.lund@digital.cabinet-office.gov.uk>
> BAU: Update to provide more details on exception in CertificateExpiryDateCheckService (Config app)

- hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/outbound/EidasAuthnRequestFromHubToAuthnRequestTransformerTest.java
- hub/config/src/test/java/uk/gov/ida/hub/config/data/ManagedEntityConfigRepositoryTest.java
- hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/IdpAuthnResponseTranslatorResourceTest.java
- hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/MatchingServiceResponseTranslatorResourceTest.java
- hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/CountryAuthnResponseTranslatorServiceTest.java
- hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorServiceTest.java
- hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/MatchingServiceResponseTranslatorServiceTest.java
- hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageSenderHandlerTest.java
- hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/HealthCheckDataTest.java
Make better use of AssertJ fluent assertions.
Applied suggestions made by @JohnWattsGDS in #414
> HUB-446: Use AssertJ better

- build.gradle
- configuration/config.yml
- configuration/policy.yml
- configuration/saml-engine.yml
- configuration/saml-proxy.yml
- configuration/saml-soap-proxy.yml
Reverts alphagov/verify-hub#426
Back out changes while I figure out what's going on.
> Revert "HUB-413 Sentry event grouping is wrong"

- build.gradle
> Fix another old Artifactory reference

- hub/config/src/main/java/uk/gov/ida/hub/config/data/ManagedEntityConfigRepository.java
- hub/config/src/main/java/uk/gov/ida/hub/config/exceptions/NoCertificateFoundException.java
- hub/config/src/test/java/uk/gov/ida/hub/config/data/ManagedEntityConfigRepositoryTest.java
- move error message into NoCertificateFoundException
> HUB-520: crash config service unable to load cert clean up

- hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApi.java
Create a Prometheus metric that counts SAML Authn Requests by an RP's entity id.
We'll surface this metric in Grafana to allow us to diagnose quality of service, spikes etc, and these can be alerted on.
This metric is emitted within the same function that the metric for "Users arriving from Govt. Service" is captured  (https://grafana.tools.signin.service.gov.uk/d/UBaTMZJWz/hub-ecs-journeys?orgId=1&var-timerange=1h&from=now-2d&to=now&refresh=1m)
> Metric for counting Authn Requests by entity id

- configuration/config.yml
- configuration/policy.yml
- configuration/saml-engine.yml
- configuration/saml-proxy.yml
- configuration/saml-soap-proxy.yml
> Accept LOG_LEVEL as an env var

- configuration/policy.yml
- configuration/saml-engine.yml
- configuration/saml-proxy.yml
- configuration/saml-soap-proxy.yml
Do https://github.com/alphagov/verify-infrastructure/pull/459 first
> Swap policy, saml-engine, saml-proxy and saml-soap-proxy to using the new Fargated config service

- configuration/policy.yml
- configuration/saml-engine.yml
- configuration/saml-proxy.yml
- configuration/saml-soap-proxy.yml
> Migrate to new config fargate service

- build.gradle
- idea.gradle
- We are replacing whitelist-repos with allowed-repos. We are running both for now so we can switch it over.
**To Review**
- Check that the URL for the allowed-repos can be accessed.
> EXErxpzy - Replace whitelist with allowlist

- Dockerfile
> BAU Upgrade the OpenJDK JRE

- hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/RpAuthnRequestTranslatorService.java
A previous commit removed the logging in favour of sending the metric.
In hindsight it might be useful to keep it as the logs give us a longer
historical record of services VSP version.
> HUB-814: Add VSP version logging back in

- hub-saml/src/main/java/uk/gov/ida/saml/core/security/AssertionsDecrypters.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/api/HubTransformersFactory.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/providers/DecoratedSamlResponseToIdaResponseIssuedByIdpTransformer.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/providers/DecoratedSamlResponseToInboundResponseFromMatchingServiceTransformer.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/response/idp/IdpResponseValidator.java
- hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/response/matchingservice/MatchingServiceResponseValidator.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/response/idp/IdpResponseValidatorTest.java
- hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/response/matchingservice/MatchingServiceResponseValidatorTest.java
see: https://govukverify.atlassian.net/browse/HUB-826
> Hub-826: only notify on all encryption key decryption failures during dual running

- hub/config/src/main/java/uk/gov/ida/hub/config/domain/IdentityProviderConfig.java
- hub/config/src/main/java/uk/gov/ida/hub/config/dto/IdpDto.java
- hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
This PR is to expose provideAuthenticationUntil in the config JSON provided to the verify-frontend app.
> HUB-853 expose provideAuthenticationUntil in JSON

- Dockerfile
Signed-off-by: Chris Mills <7100370+chriscoffee@users.noreply.github.com>
> [HUB-841] Fix casing on arguments

- .github/dependabot.yml
See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates.
This should allow us to receive dependabot PRs.
> HUB-1079 create dependabot.yml for dependabot PRs

- build.gradle
see: https://github.com/alphagov/verify-saml-libs/pull/132
> HUB-1055: Update saml-lib

- Dockerfile
Removes the root user from the main dockerfile as per best security practices
> BAU - fix dockerfile ITHC

- Dockerfile
Reverts alphagov/verify-hub#904
> Revert "BAU - fix dockerfile ITHC"

- Dockerfile
Only use the root user to assign permissions and ownership to the gradle user and use the gradle user for run commands etc.
> BAU - ITHC dockerfile fixes

- build.gradle
Co-authored-by: Paul Hennessey <paul.hennessey@digital.cabinet-office.gov.uk>
> add constraint on opensaml to pull in bcprov-jdk15on:1.67
