hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryService.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryServiceTest.java
SAML engine was updated to use correct name id policy (persistent instead of unspecified) for eIDAS Authn Request. eIDAS Authn Request and Verify Authn Request now have same name id format. As a result of this change, eIDAS Authn Response now contains correct name id format (persistent). It will pass name id format validation without errors. This means that the blanket catch of exception in policy is no longer needed.
=> EID-257: Remove blanket catch of exception

hub/config/build.gradle, hub/policy/build.gradle, hub/saml-engine/build.gradle, hub/saml-proxy/build.gradle, hub/saml-soap-proxy/build.gradle, settings.gradle
We currently deploy our app as debian packages using a custom script to
generate these. For running the apps locally, it is more convenient to use
the application plugin (distZip) to build the apps as this creates a
consistent startup script
Authors: @andy-paine
=> BAU: Add application plugin to hub apps

.dockerignore, configuration/local/config.yml, configuration/local/policy.yml, configuration/local/saml-engine.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, configuration/local/stub-event-sink.yml, docker-run.sh, run.Dockerfile
Added a Dockerfile and script that can generate an image for each
app as used by local-startup. Also moved local config files into
repo due to docker build context limitations
Added .dockerignore to speed up context loading into docker
Authors: @andy-paine
=> Firebreak: Add Dockerfile and script to run apps in container

doc/adr/0001-record-architecture-decisions.md, doc/adr/0002-accept-eidas-assertions-in-verify.md, doc/adr/0003-simple-saml-profile.md
YYYY-MM-DD is the one true date format.
Fixes #1
Authors: @richardtowers
=> Fix ADR dates to be correct and use ISO8601 format

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/PolicyState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/SessionRepository.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/StateControllerFactory.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/AbstractMatchRequestSentState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/AuthnFailedErrorStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/AwaitingCycle3DataStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/Cycle0And1MatchRequestSentStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/Cycle3MatchRequestSentStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/FraudEventDetectedStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/IdpSelectedStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/IdpSelectingStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/MatchRequestSentStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/RequesterErrorStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/SessionStartedStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/SuccessfulMatchStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/UserAccountCreatedStateTransitional.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/UserAccountCreationRequestSentStateTransitional.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/AuthnFailedErrorStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/AwaitingCycle3DataStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/Cycle0And1MatchRequestSentStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/Cycle3MatchRequestSentStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/FraudEventDetectedStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/IdpSelectedStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/RequesterErrorStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/SessionStartedStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/SuccessfulMatchStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/UserAccountCreatedStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/UserAccountCreationRequestSentStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/SessionRepositoryTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/StateControllerFactoryTest.java
Add transitional versions of state classes to be replaced to enable a zero-downtime deployment. The app will be able to consume these new versions but will not create new instances of them just yet to avoid breaking the caching and to enable ZDT deployment. If an new version is retrieved from the cache, its instance is converted into the old definition for internal use.
Authors: @CharlesIC
=> TT-1613: ZDT deployment

build.gradle, hub/config/src/main/java/uk/gov/ida/hub/config/domain/EncryptionCertificate.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/MatchingServiceConfigEntityData.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/SignatureVerificationCertificate.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/TransactionConfigEntityData.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/X509Certificate.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/MatchingServiceConfigEntityDataBuilder.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/SignatureVerificationCertificateBuilder.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/TransactionConfigEntityDataBuilder.java
Due to changes to the way DeserializablePublicKeyConfiguration works,
fed-config DTOs can no longer use that class to get certificates.
Due to an outstanding bug, we cannot use the specific subtype so
this commit ports the relevant class (and merges the abstract super)
to perform the same behaviour locally in hub.
There is a plan to eventually migrate these DTOs to a database rather
than file backed system in which case this issue will be redundant
Authors: @andy-paine
=> BAU: Port class from security-utils to support x509 certs in fed config

build.gradle, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyApplication.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/exception/PolicyApplicationExceptionMapper.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/logging/HubEventLogger.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/PolicyApplicationTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyApplication.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/SamlProxyApplicationTest.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyApplication.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyApplicationTest.java
Adding a configurable toggle to policy, saml soap proxy and saml proxy to send or not to send events to a new recording system (not Event Sink). The default is not to send events to the recording system since the recording system is not set up in production at this moment. Please note that this change does not affect Hub sending events to Event Sink. 
=> ABD-35: Add a feature toggle to send events to a recording system

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/SessionTimeoutIntegrationTests.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ExternalCommunicationEventLoggerTest.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/logging/ExternalCommunicationEventLoggerTest.java
This integration test ensures that Hub can send events to Event Emitter without any errors.
Update unit tests to ensure that event id is present in an event message before sending it to Event Sink and Event Emitter.
=> ABD-35: Update an integration test to include event emitter

build.gradle, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/SessionTimeoutIntegrationTests.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyApplication.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/PolicyApplicationTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyApplication.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/SamlProxyApplicationTest.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyApplication.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyApplicationTest.java
The latest version of rest-utils supports the ability to send encrypted events to either a source queue or a stub queue. If the source queue name is not present, encrypted event messages will be sent to the stub queue. If the source queue is present, encrypted event messages will be sent to the source queue. The stub queue will just write the encrypted event message to the standard output.
=> ABD-35: Upgrade to use latest version of rest-utils

hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/HubMetadataIntegrationTests.java
rather than coverting to a custom Dto object and then comparing it's not
difficult to instead read the Saml object as an `EntityDescriptor` and
then assert on the things we care about.
This should allow us to delete a bunch of dead code in verify-hub-saml.
=> refactor: assert metadata directly in tests

hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/MetadataRefreshTaskIntegrationTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/MetadataRefreshTaskIntegrationTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/MetadataRefreshTaskIntegrationTest.java
These seem to have been removed?
Pair: WillPa
=> bau: make sure metadata refresh tasks are available on admin port

build.gradle
It contains changes in metadata bindings to make the eIDAS metadata resolver factory thread safe.
=> BAU: Use a later version of the SAML libs

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/factories/EidasValidatorFactory.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/factories/EidasValidatorFactory.java
There was a race condition in `EidasValidatorFactory` where it was assigning
signature validators into member fields when validating an eidas
signature. Two calls to the validate functions from different threads
could lead to the wrong validator being used on a message.
=> bau: fix threaded race condition

hub/policy/src/main/java/uk/gov/ida/hub/policy/services/Cycle3Service.java
This avoids a potential race condition where the MSA responds to Verify
before the states in Policy have finished replicating.
The states in Policy are stored in a distributed cache, which has
synchronous writes. If we update the state before sending the matching
request it will block until all instances of Policy have updated their
state. This avoids the situation where a matching response arrives at an
instance of Policy which is still in a state where that is not
permissible.
This commit does have a potentially negative impact on the error
handling in the situation where the call to `sendAttributeQueryRequest`
fails. Previously the user would remain in `AwaitingCycle3InputState`,
which would have allowed them to recover from this error by (e.g.)
clicking back on the Something Went …
=> TT-2120: Transition state before sending matching request

build.gradle, configuration/local/saml-engine.yml, configuration/local/saml-soap-proxy.yml, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/test/resources/saml-engine.yml, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
Change SAML Engine, SAML SOAP Proxy and SAML Proxy to use the non-deprecated class 'TrustStoreBackedMetadataConfiguration' instead of the deprecated class 'TrustStorePathMetadataConfiguration'.
Update to use the latest version of verify-saml-libs to enable the non-deprecated class TrustStoreBackedMetadataConfiguration to ignore unknown json properties.
Replace truststore with trustStore in SAML Engine, SAML SOAP Proxy and SAML Proxy config files.
Co-authored-by: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
Co-authored-by: Kornelis Sietsma <kornelis.sietsma@digital.cabinet-office.gov.uk>
=> Bau update to use non deprecated class for trustStore config

build.gradle, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/test/resources/saml-engine.yml, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
Update the config in saml-engine, saml-soap-proxy and saml-proxy to use
the new logic in verify-saml-libs for
MultiTrustStoreBackedMetadataConfiguration.
Co-authored-by: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
=> HUB-101: Update config to use new logic

build.gradle, configuration/local/config.yml, configuration/local/policy.yml, configuration/local/saml-engine.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/config/src/main/java/uk/gov/ida/hub/config/truststore/TrustStoreForCertificateProvider.java, hub/config/src/test/resources/config.yml, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/builders/PolicyConfigurationBuilder.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/test/resources/policy.yml, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/CryptoModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/config/TrustStoreForCertificateProvider.java, hub/saml-engine/src/test/resources/saml-engine.yml, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/config/TrustStoreForCertificateProvider.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/TrustStoreForCertificateProvider.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
Update to use latest version of verify-utils-libs which removes the getClientTrustStoreConfiguration method from the TrustStoreConfiguration interface. Client truststore is not used anymore for Certificate Chain Validation for Hub or IDP trust stores. This is now all done by a filter in the Metadata Resolver. Certificate Chain Validation is still done for the RP truststore so the overall function needs to remain.
Remove clientTrustStore from config files.
=> Hub 103: remove client truststores

configuration/local/config.yml, configuration/local/policy.yml, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/config/src/main/java/uk/gov/ida/hub/config/truststore/TrustStoreForCertificateProvider.java, hub/config/src/test/resources/config.yml, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/builders/PolicyConfigurationBuilder.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/test/resources/policy.yml
Policy and config use client truststore for other purposes and they do not use
metadata resolver to perform certificate chain validation on hub SAML signature
and encryption certificates and identity providers SAML signature certificates
in hub federation metadata file.
Co-authored-by: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
=> HUB-103: Add client truststore back to policy and config

hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogger.java
Currently the ProtectiveMonitoringLogFormatter logs something which at
first glance may appear to be JSON. It has {} and keys/values separated
by : however don't be fooled. This is not JSON, there are no quotes "!.
This change places attributes which were part of the LogFormatter into
the MDC which is included in the Logstash output as JSON. Having
structured logs makes it easier to query them through ELK.
As this change doesn't alter the message logged it shouldn't impact any
current users of the logs (e.g. SecOps).
=> Log useful request / response attrs as JSON

hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageSenderHandler.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogFormatter.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogger.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/repositories/SignatureStatus.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApi.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageSenderHandlerTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogFormatterTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLoggerTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApiTest.java
Previously we were using a Boolean type to represent the following
- null: no signature on the request/response
- false: signature present but not valid
- true: signature present and valid
This can be problematic as null checks need to be carefully performed.
These checks were missing in a035bb51a2f469022dbb25bd163e4d9a49d3ce8b
This commit replaces the usage of `null` with a separate isSigned
boolean. The change is only necessary for when processing Response
objects as they have this option of being unsigned (simple profile).
=> Remove boxed Boolean type from ProtMonLogging

hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageSenderHandler.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogFormatter.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogger.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/repositories/SignatureStatus.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApi.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageSenderHandlerTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogFormatterTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLoggerTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApiTest.java
In some cases the Hub will not sign Responses (relying on signed
assertions) and this logging would error with a NullPointerException.
This change separates the states of not having a signature and that
signature not being valid to better represent what is happening.
=> Handle cases where validSignature is null

hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/OutboundLegacyResponseFromHubToStringFunctionSHA256.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/OutboundSamlProfileResponseFromHubToStringFunctionSHA256.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/factories/OutboundResponseFromHubToResponseTransformerFactory.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/proxy/TransactionsConfigProxy.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/factories/OutboundResponseFromHubToResponseTransformerFactoryTest.java
Switch between SHA1 and SHA256 signing depending on a flag in the transaction configuration.
Flag currently hard-coded to stay on SHA1, pending corresponding changes to the config component.
=> VCU-43: Configurable Signing Algorithm per Service

.travis.yml, README.md, build.gradle, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLoggerTest.java, idea.gradle
Using the same VERIFY_USE_PUBLIC_BINARIES environment variable as in the
libraries to flag the us of the bintray binaries.
This will mean that:
1) Third parties can build hub without access to our private artifactory
2) We will have nice travis-y PR builds in hub
3) We can display a nice build status badge in the readme
Also discovered that there were three tests that would fail if LOG LEVEL was
set higher than INFO (which it is on Travis), due to a missing side effect of
the console logger. These are a bit more robust now thanks to a pretty hacky
call to `getMDCPropertyMap()`.
=> bau: Build verify-hub in travis

jenkins.sh
I thought the hub-saml jenkins job would do this, but it looks like that
job is actually a vestige of before we moved hub-saml into hub and
archived the repo.
verify-hub's jenkins job isn't JJB'd, so I'll set up the relevant bits
in the jenkins UI.
=> bau: Publish hub-saml to bintray

hub/policy/build.gradle
Allows unit tests to pass under Java 10.
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>
=> VCU-27: Upgrade EqualsVerifier to 2.4.5.

hub/saml-engine/build.gradle, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/security/NumberedPipeReader.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/security/SharedSecretsWrapper.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/security/EncryptionKeysFromFileDescriptorsTest.java
Temporary change to load SharedSecrets via Reflection.
Allows compilation and execution on Java 8, 9 and 10.
To be removed on final upgrade to Java 10.
Co-authored-by:  Alan Carter <alan.carter@digital.cabinet-office.gov.uk>, javindo
=> VCU-96: Use of SharedSecrets compatible with Java 8, 9 and 10.

hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java
- We are likely to be changing the format of this config quite
a lot as we iterate on it so to have slightly fewer releases it is
nice to be able to ignore unknown properties
Co-authored-by: Brendan Butler <brendan.butler@digital.cabinet-office.gov.uk>
=> BAU: Allow unknown properties on event emitter config

.gitignore
local.env is a generated file and is used for local environment. It does not need to be committed to GitHub.
=> BAU: Ignore local.env file

build.gradle, configuration/local/policy.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, debian/policy/policy.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/test/resources/policy.yml, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
The event emitter should be able to use AWS credentials to connect to SQS.
Co-authored-by:
Aditya Pahuja <aditya.pahuja@digital.cabinet-office.gov.uk>
Daniel Besbrode <daniel.besbrode@digital.cabinet-office.gov.uk>
https://trello.com/c/8Xm7DiDy/29-deploy-current-mvp-components-in-joint-test-environment
=> TRELLO-8Xm7DiDy: Update event emitter to the latest version

build.gradle, configuration/local/policy.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, debian/policy/policy.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/test/resources/policy.yml, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
Reverts alphagov/verify-hub#93. We need to do some cross account configuration to get this working correctly
=> Revert "TRELLO-8Xm7DiDy: Update event emitter to the latest version"

build.gradle, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/support/AssertionDecrypter.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java
- Give eidas flow support to the encryption algorithms for content
encryption and key transport as in the eidas crypto spec. 
- Renamed method Named attribute in SamlEngineModule as it is only used for Eidas and doesn't just use AES256 anymore.
- The best place to test this would be from StubCountry, encrypting the assertion using the algorithms in the crypto spec. This would give full end to end coverage. 
- This change will cover EID-817 and EID-820
=> EID-817 - Give eidas support for required algorithms

hub-saml/src/main/java/uk/gov/ida/saml/core/validators/subject/AssertionSubjectValidator.java, hub-saml/src/test/java/uk/gov/ida/saml/core/validators/subject/AssertionSubjectValidatorTest.java
The German eIDAS Middleware returns NameIDs with the format set to
*transient*. Normally, Verify IDPs return *persistent*. We should allow
the validator to accept both types of NameID since it doesn't really
affect the journey.
=> EID-842: Accept transient NameIDs

build.gradle, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/CountryAuthnResponseTranslatorResourceTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/CountryAuthnResponseTranslatorServiceTest.java
- Was previously AES256-CBC, should have been AES128-GCM as in the spec.
- Create tests to generate Saml Response using different encryption algorithms,
so we can ensure that Hub can handle them.
=> EID-820 - Use correct algorithm when decrypting eidas assertions

build.gradle, configuration/local/policy.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, debian/policy/policy.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml, hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java, hub/policy/src/test/resources/policy.yml, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
- Modify config classes and files to provide encryption key
directly instead of relying on KMS/S3 lookups
=> TRELLO-8Xm7DiDy: Make config provide encryption key

build.gradle
The event emitter now serializes timestamps for each event as time since epoch in milliseconds instead of sending a java datetime object
=> User latest version of event emitter

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/TestSessionRepository.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/InfinispanStartupTasks.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/SessionRepository.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/SessionRepositoryTest.java
the info contained within the datetime_cache is available in the state_cache,
datetime_cache only contains SessionId mapped to state.getSessionExpiryTimestamp()
This commit removes the datetime_cache so only one session cache exists
Following this coming up in a chat with @andy-paine
=> remove an unnecessary infinispan cache in policy - datetime_cache

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/TestSessionRepository.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/InfinispanStartupTasks.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/SessionRepository.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/SessionRepositoryTest.java
Reverts alphagov/verify-hub#113
I've been thinking about this - we need to stop using the cache before finally removing it
If this gets deployed then when a new session is started on a new policy, it won't be in the datetime_cache in an old policy - so an incorrect SessionNotFoundException will be thrown if the load balancer points the user to the older policy.  
Firstly the change need to be made to switch to checking the state_cache instead of datetime_cache, but still populate the datetime_cache, then the datetime_cache can be removed.
=> Revert "remove an unnecessary infinispan cache in policy - datetime_cache"

hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/SessionRepository.java
the info contained within the datetime_cache is available in the state_cache,
datetime_cache only contains SessionId mapped to state.getSessionExpiryTimestamp()
This commit keeps datetime_cache populated so that old policy instances can
keep working without interruption for users, and after a release another commit
will remove the cache entirely.
=> stop using unnecessary infinispan cache in policy - datetime_cache

build.gradle, configuration/local/policy.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, debian/policy/policy.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml, hub/policy/src/main/java/uk/gov/ida/hub/policy/EventEmitterConfiguration.java, hub/policy/src/test/resources/policy.yml, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
B&A: Upgrade Event Emitter Library in Hub.
https://trello.com/c/auJ7kBAx
Uplift Event Emitter library version.
Add url field and provide default values for event emitter url in config.
Co-authored-by: Brendan Butler <brendan.butler@digital.cabinet-office.gov.uk>
=> Event emitter upgrade in hub

debian/config/upstart/config, debian/policy/upstart/policy, debian/saml-engine/upstart/saml-engine, debian/saml-proxy/upstart/saml-proxy, debian/saml-soap-proxy/upstart/saml-soap-proxy
- The JAVA_HOME doesn't work on our AWS envs so just unset it
- Also quote your variables.
=> BAU: Fix upstart scripts

configuration/local/policy.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, debian/policy/policy.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml, hub/policy/src/test/resources/policy.yml, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
- GATEYWAY sounds more friendly but Puppet expects to use GATEWAY
=> BAU: Fix typo in env var

debian/policy/upstart/policy
Introduced in an earlier change today, its causing upstart to fail and a
broken joint.
Solo
=> BAU: Fix typo - missing closing quotes

configuration/local/saml-engine.yml, debian/saml-engine/saml-engine.yml, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/test/resources/saml-engine.yml
This reverts commit 736c581173a65e0a3fa244733c69699613f3ffd9.
Whilst we do not need the signing certificate for the regular Verify
federation, we do need it for communicating with EU countries via eIDAS.
The KeyInfo part of the SAML message needs the full X.509 certificate, not just
the public key.
Reintroduce the SAML signing certificate for now - we may be able to retrieve
it from SAML metadata in future.
=> Revert "BAU: Remove hub SAML signing certificate from SAML Engine"

build.gradle, hub-saml/src/test/java/uk/gov/ida/saml/hub/api/HubTransformersFactoryTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java
- The bug in saml-libs means that it will not throw an exception
when keyinfo is required and the signing cert is not there. This has been
resolved in the latest version of saml-libs.
- Remove meaningless comment in code
- Add test to ensure exception is thrown when signing cert is not present
=> EID-939 - Update latest saml-libs to fix bug

build.gradle, debian/policy/policy.yml, hub/policy/build.gradle, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyApplication.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyConfiguration.java
This adds PrometheusBundle from alphagov/gds_metrics_dropwizard.  This
adds configurable support for prometheus metrics to be exposed at
/prometheus/metrics on the admin port.  By default, this endpoint is
disabled; it is activated by adding `prometheusEnabled: true` to
policy.yml.
Policy was chosen arbitrarily as a proof of concept; there's no reason
we couldn't do the same for all apps.
In order for this to work, the gds-metrics-dropwizard dependency will
need to be added to artifactory.
=> Add prometheus support to Policy behind a feature flag

hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/MetadataConsumerTests.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/SamlMessageReceiverApiResourceTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyApplication.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/factories/EidasValidatorFactory.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/security/AuthnResponseKeyStore.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/security/HubSigningKeyStore.java, hub/saml-proxy/src/test/resources/saml-proxy.yml
Reverts alphagov/verify-hub#48
This is causing some issues on joint and locally as the new code isn't able to find the Hub's eIDAS entity ID from the the normal federation metadata, which it needs to resolve the Hub's signing certificates. The previous code hardcoded the entity ID for lookup on the federation metadata.
=> Revert "fb: use new signature validators in saml-proxy"

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasMatchingServiceResourceIntegrationTest.java
Some tests in EidasMatchingServiceResourceIntegrationTest got incorrect or mixed up names whilst merging b1633eed0da49c9bac616d6b36e415b5a41037b3.
This was spotted whilst going through the tests during sign-off
=> EID-885: Correct some tests names in EidasMatchingServiceResourceIntegrationTest

debian/config/upstart/config, debian/policy/upstart/policy, debian/saml-engine/upstart/saml-engine, debian/saml-proxy/upstart/saml-proxy, debian/saml-soap-proxy/upstart/saml-soap-proxy
- I mistakenly made all the memory allocations for the apps the same
- This puts the allocations into an env var so that puppet can set it as
it used to when it layed down the upstart files
=> BAU: Let puppet set memory allocations

hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/CountryAuthenticationStatus.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/CountryAuthenticationStatusUnmarshaller.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToCountryAuthenticationStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToCountryAuthenticationStatusMappingsFactory.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/CountryAuthenticationStatusUnmarshallerTest.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/CountryAuthenticationStatus.java
Add the new CountryAuthenticationStatus enum and unmarshaller so we can handle authn responses specific to eIDAS and Countries.
Currently, we're re-using IdpIdaStatus enum to handle authn responses from Countries. This enum is not well-fitted for eIDAS, though, because the SAML responses from IDPs and Countries and their properties vary significantly for any journey that's not a success. The Country status definitions will allow us to handle eIDAS-specific responses better and customise them without affecting the Verify flow.
At the moment, we're only interested in mapping all the authn responses from Countries to either of the two outcomes - Success or Failure (defined in the `CountryAuthenticationStatus` enum). If in the future we need to get more granular, we can easily add more …
=> EID-951: Add CountryAuthenticationStatus enum and unmarshaller

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasMatchingServiceResourceIntegrationTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasSessionResourceIntegrationTest.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/InboundResponseFromCountry.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryService.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/CountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryServiceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/CountryAuthnResponseTranslatorResourceTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/resources/translators/CountryAuthnResponseTranslatorResource.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/CountryAuthnResponseTranslatorService.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/CountryAuthnResponseTranslatorServiceTest.java
_These changes depend on_ #147
Switch to using the new eIDAS specific `CountryAuthenticationStatus` when handling authn responses from Countries
In **saml-engine**:
- Make `CountryAuthnResponseTranslatorService` use the new `CountryAuthenticationStatusUnmarshaller` instead of the IDP one to map the status of an authn response from a country
- `CountryAuthnResponseTranslatorResource` will return one of the values in the new CountryAuthenticationStatus.Status enum to the caller
In **policy**:
- Make the type of the Status field in `InboundResponseFromCountry` to be the new `CountryAuthenticationStatus` instead of re-using `IdpIdaStatus` for eIDAS journeys
- `AuthnResponseFromCountryService` now handles the country specific mapped responses. At the moment this can only be Success or Failure …
=> EID-951: Use CountryAuthenticationStatus when handling authn responses from Countries

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/ResponseFromCountryValidator.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/ResponseFromCountryValidatorTest.java, ruleset.xml
Make `ResponseFromCountryValidator` allow non-successful auth responses from Countries to contain unencrypted assertions.
In the eIDAS world, authn responses are allowed to have unencrypted assertions if they don't have the "Success" status. Some countries include such assertions in their Cancel responses but currently ResponseFromCountryValidator throws and exception and we can't handle this type of failure in a graceful manner, so the users see the "Service unavailable" error page. If we allow these to pass, then the users will see the new error page with a better message and a link to retry the journey.
Some of the countries that send such responses are Germany and any country that uses the CEF Reference Node (e.g. Belgium and Estonia).
=> EID-951: Allow Country non-successful auth responses to contain unencrypted assertions

hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/TransactionsResourceIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/TransactionConfigEntityData.java, hub/config/src/main/java/uk/gov/ida/hub/config/dto/TransactionDisplayData.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/TransactionsResource.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/TransactionConfigEntityDataBuilder.java
Add new config value to transaction resources for the service's headless journey start page.
Ensure new value is returned in enabled transaction list
=> HUB-264 - Add Headless Redirect Links to Pause Page

hub-saml/src/main/java/uk/gov/ida/saml/hub/api/HubTransformersFactory.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/AuthenticationStatusFactory.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/CountryAuthenticationStatus.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/IdpIdaStatus.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/AuthenticationStatusUnmarshallerBase.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/CountryAuthenticationStatusUnmarshaller.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/IdpIdaStatusUnmarshaller.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToAuthenticationStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToCountryAuthenticationStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToIdaStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToIdpIdaStatusMappingsFactory.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/response/idp/components/EncryptedResponseFromIdpValidator.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/IdpIdaStatusUnmarshallerTest.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/response/idp/components/EncryptedResponseFromIdpValidatorTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/ResponseFromCountryValidator.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorServiceTest.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/ResponseFromCountryValidatorTest.java
Added a few interfaces and did some refactoring that will be needed later on to enable us to instantiate the response validator with an appropriate mapper class (either eIDAS or Country version).
New interfaces:
- `AuthenticationStatusFactory`
- `SamlStatusToAuthenticationStatusCodeMapper`
Refactored `IdpIdaStatusUnmarshaller` and `CountryAuthenticationStatusUnmarshaller` to inherit from a Base class as they both had identical logic
=> EID-951: Use eIDAS specific logic for validation of authn responses from countries [1/2]

hub-saml/src/main/java/uk/gov/ida/saml/hub/api/HubTransformersFactory.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/CountryAuthenticationStatusUnmarshaller.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToAuthenticationStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToCountryAuthenticationStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToIdaStatusCodeMapper.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/response/idp/components/EncryptedResponseFromIdpValidator.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/CountryAuthenticationStatusUnmarshallerTest.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/response/idp/components/EncryptedResponseFromIdpValidatorTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/CountryAuthnResponseTranslatorService.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/ResponseFromCountryValidator.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/CountryAuthnResponseTranslatorServiceTest.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/ResponseFromCountryValidatorTest.java
Use `ResponseFromCountryVaidator` so that we use eIDAS specific logic for validation of authn responses from countries
_These changes depend on the refactoring in #150_
- Refactor `CountryAuthenticationStatusUnmarshaller` to inherit from the Base class
- Change the `EncryptedResponseFromIdpValidator` to work with Countries or IDPs by passing in the appropriate mapper to the constructor
=> EID-951: Use ResponseFromCountryVaidator for validation of authn responses from countries [2/2]

hub/config/src/main/java/uk/gov/ida/hub/config/ConfigModule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java
Modules classes create a new instance of ObjectMapper that is not same as the instance of ObjectMapper provided by DropWizard. This results in logging timestamp not following the ISO8601DateFormat. The fix is to get Modules classes to use the existing ObjectMapper provided by the DropWizard instead of a new instance of ObjectMapper. This will allow applications to log timestamp in the ISO8601DateFormat.
I ran pre-commit and hub acceptance test. They passed.
=> BAU: Update to use ObjectMapper provided by DropWizard

hub-saml/src/test/java/uk/gov/ida/saml/metadata/HubMetadataPublicKeyStoreTest.java, hub-saml/src/test/java/uk/gov/ida/saml/metadata/IdpMetadataPublicKeyStoreTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/IdentityProviderResourceIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/IdentityProviderConfigEntityData.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactory.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/NewUserIdpPredicate.java, hub/config/src/main/java/uk/gov/ida/hub/config/dto/IdpDto.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/IdentityProviderConfigEntityDataTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/IdentityProviderConfigDataBuilder.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactoryPredicatesTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactoryTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/NewUserIdpPredicateTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/OnboardingIdpPredicateTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/PredicateTestHelper.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/SupportedLoaIdpPredicateTest.java
This PR updates the config service to handle the two new properties `provideRegistrationUntil` and `provideAuthenticationUntil` that can be set in IDP configurations. For the LOA endpoint, all IDPs will now be returned up until `provideRegistrationUntil`. For the sign-in endpoint, all IDPs will continue to be returned with an additional property `authenticationEnabled`, based on the `provideAuthenticationUntil` property.
The PR also includes a cherry-picked commit from @kerrr (on the recommendation of @rhowe-gds ) to fix the failing test in IdpMetadataPublicKeyStoreTest.java (on Travis).
=> Add support to set registration and authentication expiry dates in IDP configurations

build.gradle
Uplift verify-saml-libs version to import changes in the library.
https://github.com/alphagov/verify-saml-libs/commit/d6f871b7d942e828e0ba6ec90032959aac847687
Healthcheck and unit tests now succeed when there are no trust anchors.
Changed healthcheck output to be more structured.
Returns details on each failure.
Co-authored-by: Simon Worthington <simon.worthington@digital.cabinet-office.gov.uk>
Co-authored-by: dbes-gds <daniel.besbrode@digital.cabinet-office.gov.uk>
=> BAU: Change test behaviour when no Eidas Metadata.

bin/build.rb
The orchestration ready script depends on httplib2
=> BAU: Add python-httplib2 dependency to Debian packages

.travis.yml
Oracle JDK10 now end of life.
Java 9 SDKs not required to be supported by the Hub.
openjdk10 failures not ignored.
=> BAU: Rationalise Java SDK versions used by Travis.

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/AuthnRequestFromTransactionResourceIntegrationTest.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/Urls.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandler.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasAuthnFailedErrorStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasUserAccountCreationFailedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/RestartJourneyStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasAuthnFailedErrorState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCountrySelectedState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasUserAccountCreationFailedState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/RestartJourneyState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/resources/AuthnRequestFromTransactionResource.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandlerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java
Currently, if a user selects a country or an IDP without completing verification and clicks the back button to the journey picker page and then attempts a different type of journey, they receive a "service unavailable" error page as Policy doesn't allow a transition between `IdpSelected` and `EidasCountrySelected` states. The solution to this is to allow the frontend to ask Policy to restart the journey back to `SessionStartedState` when a user goes back to the journey picker page (`/prove-identity`) and selects a different type of journey. We already allow this for some eIDAS states.
This piece of work makes the interfaces more general so that we can apply the same to the `IdpSelected` state later. This commit only affects eIDAS -> Verify transitions. Transitions in the opposite …
=> EID-1004: Fix transition between Verify and eIDAS journeys (part 1/2)

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/AuthnRequestFromTransactionResourceIntegrationTest.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/Urls.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCountrySelectedState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/IdpSelectedState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/resources/AuthnRequestFromTransactionResource.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateControllerTest.java
Currently, if a user selects an IDP without completing verification and clicks the back button to the journey picker page and then attempts an eIDAS journey, they receive a "service unavailable" error page as Policy doesn't allow transitions from `IdpSelected` to `EidasCountrySelected` states. The solution to this is to allow the frontend to ask Policy to restart the journey back to `SessionStartedState` when a user goes back to the journey picker page (`/prove-identity`) and selects a an eIDAS journey. We already allow this for eIDAS journeys when a user goes back and selects a Verify journey.
This piece of work enables transitions from a Verify journey to an eIDAS journey. Transitions on the opposite direction were enabled in [part 1](https://github.com/alphagov/verify-hub/pull/155). …
=> EID-1004: Fix switching between Verify and eIDAS journeys (part 2/2)

hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/TransactionsResourceIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/TransactionConfigEntityData.java, hub/config/src/main/java/uk/gov/ida/hub/config/dto/TransactionSingleIdpData.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/TransactionsResource.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/TransactionConfigEntityDataBuilder.java
Amend TransactionDisplayData and TransactionConfigEntityData to include new singleIdpStartpage attribute
Amend TransactionResource to populate this new field in calls.
Co-authored-by: Callum Knights <callum.knights@digital.cabinet-office.gov.uk>
=> HUB-274: Support alternative service URLs in single IDP journeys

hub-saml/src/main/java/uk/gov/ida/saml/hub/validators/authnrequest/DuplicateAuthnRequestValidator.java
- Also support instantiating a validator with just
a simple `Duration` object.
=> EID-1088 Allow usage of DuplicateAuthnRequestValidator outside of Hub

hub-saml/src/main/java/uk/gov/ida/saml/core/validators/assertion/DuplicateAssertionValidator.java, hub-saml/src/main/java/uk/gov/ida/saml/core/validators/assertion/DuplicateAssertionValidatorImpl.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/api/HubTransformersFactory.java, hub-saml/src/test/java/uk/gov/ida/saml/core/validators/assertion/DuplicateAssertionValidatorTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java
- So it can be used with a different implementation in proxy node
Co-authored-by: Simon Worthington <simon.worthington@digital.cabinet-office.gov.uk>
=> EID-1117 - Turn DuplicateAssertionValidator into interface

build.gradle, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/OutboundResponseFromHubToSamlResponseTransformer.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/SimpleProfileOutboundResponseFromHubToSamlResponseTransformer.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/outbound/OutboundResponseFromHubToSamlResponseTransformerTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/RpAuthnResponseGeneratorResourceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/builders/ResponseFromHubDtoBuilder.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/contracts/ResponseFromHubDto.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/RpAuthnResponseGeneratorService.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/RpErrorResponseGeneratorService.java
- For the non-matching journey, we need to support sending a List of assertions in ResponseFromHubDto, rather than just one.
- The new List of assertions is used everywhere internally, but to achieve ZDD, we currently retain the encryptedMatchingServiceAssertion field.  Both the list and the original field get populated.
https://trello.com/c/lKH7U7yW/185-wrap-assertions-in-hub-response-to-handle-idp-assertions
Solo: @alan-gds
=> lKH7U7yW: Allow lists of assertions in response

hub-saml/src/main/java/uk/gov/ida/saml/core/domain/InboundResponseFromIdpData.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/InboundResponseFromIdp.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/IdaResponseFromIdpUnmarshaller.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/InboundResponseFromIdpDataGenerator.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasMatchingServiceResourceIntegrationTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasSessionResourceIntegrationTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/SessionResourceAuthnResponseFromIdpIntegrationTests.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/SessionResourceIntegrationTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/builders/InboundResponseFromIdpDtoBuilder.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/InboundResponseFromCountry.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/InboundResponseFromIdpDto.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/ResponseAction.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryService.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromIdpService.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/domain/InboundResponseFromIdpDtoBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryServiceTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromIdpServiceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/IdpAuthnResponseTranslatorResourceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/builders/AuthnResponseFactory.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/domain/InboundResponseFromIdpDto.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorService.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/logging/UnknownMethodAlgorithmLoggerTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/MetadataConsumerTests.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/PolicyStubRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/domain/ResponseActionDto.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApiTest.java
Front end needs to know when the SAML Response from an IDP stops being valid according to the NotOnOrAfter attribute of the Conditions element for the user's assertion.
We have exposed this as a value in the ResponseAction from policy, which in turn gets it from saml engine via saml proxy.
At this stage all relevant tests have been modified so that the NotOnOrAfter is null, a valid condition.
=> Hub 348 expose notonorafter

hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/IdaResponseFromIdpUnmarshaller.java
The NotOnOrAfter value we validate is part of the assertion's Subject.
Follows the same logic like in this validator: https://github.com/alphagov/verify-hub/blob/cd949e9aed8ea2dd6d9a5d376cacb60f26348465/hub-saml/src/main/java/uk/gov/ida/saml/core/validators/assertion/DuplicateAssertionValidatorImpl.java#L38
The actual underlying failed validation gets triggered by reading the Subject instead of Conditions.
https://github.com/alphagov/verify-hub/blob/cd949e9aed8ea2dd6d9a5d376cacb60f26348465/hub-saml/src/main/java/uk/gov/ida/saml/core/validators/subjectconfirmation/BasicAssertionSubjectConfirmationValidator.java#L29
=> BAU: Fix the retrieval of the NotOnOrAfter attribute

hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/RpAuthnResponseGeneratorResourceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/builders/ResponseFromHubDtoBuilder.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/contracts/ResponseFromHubDto.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/RpAuthnResponseGeneratorService.java
- Policy now only uses the list of assertions so we never expect to get
this value anymore so can safely delete
- Deleted previously added tests that demonstrated the fallback
behaviour whilst dual running
=> lKH7U7yW: Remove old encryptedMatchingDataset assertion

hub-saml-test-utils/build.gradle, hub-saml/build.gradle
- There appears to be an issue with bintray version 1.8.0 and gradle version 4.8 or later.
- The issue is that the upload uri is constructed incorrectly and causes the bintrayUpload task to fail. 
- More information can be found on this issue here - https://github.com/bintray/gradle-bintray-plugin/issues/234
=> bau - upgrade bintray version to 1.8.4

hub/config/src/main/java/uk/gov/ida/hub/config/domain/TranslationData.java
Added singleIdpStartPageContent attribute to translation data.
Co-authored-by: Kerr Rainey <kerr.rainey@digital.cabinet-office.gov.uk>
=> HUB-399: Create a SIDP customised start page for SA in the hub

.travis.yml, build.gradle
- The JAXB APIs have been completely removed from the JDK in Java 11.
- Add JAX-B API as a dependency.
- Don't allow failures with openjdk10 or openjdk11 with travis.
=> EID-1183 - Allow Hub to run on Java11

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasSessionResourceIntegrationTest.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryService.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryServiceTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/AbstractContextExceptionMapper.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxyApplicationExceptionMapper.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/AbstractContextExceptionMapperTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxyApplicationExceptionMapperTest.java
Currently, if a user fails authentication with the Middleware and and goes back and retries, Policy will throw an `INVALID_STATE` exception. SAML Proxy will pick that up and in turn return an HTTP response. Frontend expects a JSON body, however, and cannot parse the response. The JSON library code throws an exception that may be handled at the top level. In prod users get correctly redirected to the "Something went wrong page" but we see an entry in Sentry every time with the message ```Couldn't parse JSON``` instead of the actual exception message. In non-prod environments, devs see the Ruby error page.
Summary of changes:
- **FIX 1: Send JSON in the response body from SAML Proxy so frontend can handle it**
- Add a line to `AbstractContextExceptionMapper` in SAML Proxy to make sure that …
=> EID-1015: Unhandled exception when user fails MW auth and goes back to re-submit form

hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java
This removes @NotNull from eventSinkUri in policy, saml proxy and saml
soap proxy.  It also changes their respective modules to register a
no-op EventSinkProxy implementation if eventSinkUri is not provided.
All environments now support the new eventEmitterConfiguration option
instead so eventSinkUri is no longer required.
=> make eventSinkUri an optional configuration parameter

debian/policy/policy.yml, debian/saml-engine/saml-engine.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml
We need to rotate the microservice tls cert
The puppet module we are using that builds the keystore only supports
one key and cert
While we rotate the key and cert we need the httpClient to not care
whether the cert is in the truststore or not
This only affects internal TLS as the external truststores are separate
We will do the rotation in puppet after this goes out
=> Prepare to rotate microservice tls cert

debian/config/config.yml, debian/saml-engine/saml-engine.yml, debian/saml-proxy/saml-proxy.yml, debian/saml-soap-proxy/saml-soap-proxy.yml, hub/config/build.gradle, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigApplication.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/config/src/test/resources/config.yml, hub/saml-engine/build.gradle, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineApplication.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/test/resources/saml-engine.yml, hub/saml-proxy/build.gradle, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyApplication.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/build.gradle, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyApplication.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
This pull requests adds Prometheus Bundle to Config, SAML Engine, SAML Proxy and SAML SOAP Proxy applications. This change introduces a new configuration item (prometheusEnabled). If `prometheusEnabled` is true then Prometheus metrics endpoint (/prometheus/metrics) will be enabled on the admin port and this will allow Prometheus server to scrape metrics from the application's endpoint.  Policy already has Prometheus Bundle and no change is required.
=> AUTO110: Add Prometheus bundles to all applications

build.gradle, hub/saml-engine/build.gradle, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/HealthCheckTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/HealthCheckWithoutCountryTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/exceptions/MissingMetadataException.java
It pulls in a few new things.
An update to EidasMetadataResolverRepository to throw an exception
instead of an error if it encounters certificate that's expired. This is
useful in saml-engine and saml-proxy.
MetadataResolverBundle has been updated to generate a dropwizard
healthcheck for the metadata, rather than the app itself having to do
it. This meant the healtcheck being created in saml-engine could be
removed.
It allows optional metadata bundling, which required an update to the
config class for saml-engine as well as saml-soap-proxy to support
Optionals being returned by `getMetadataConfiguration`. The metadata is
always not null in these cases to impact is minimal.
=> EID-1072 Bump saml-libs to version 169

hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApi.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApiTest.java
For [this ticket](https://govukverify.atlassian.net/browse/EID-1240) which was spawned from [this zendesk support ticket](https://govuk.zendesk.com/agent/tickets/3563798).
The current error message when an authn request has an invalid signature doesn't give much info about where the request came from. By adding the issuer we can start to make more sense of the error messages.
=> EID-1240 Improve error log message for invalid authn signature

hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/resources/AttributeQueryRequestSenderResource.java
- In commit 22cca62 we added `@ResponseMetered` annotations to the
SAML-Proxy endpoints and have used them to monitor the "success %age"
of our SAML requests in Hub
- As requests to SAML SOAP Proxy do not go through SAML Proxy, errors
occurring when sending AQRs aren't currently tracked
- Adding this metric will mean that we can track the number of errors
being thrown in the endpoint
- By monitoring the endpoint itself, we only report on when a request
completely fails (so if an attempt fails but passes in a future retry
this metric reports it as OK)
=> ZD-3567692: Add error metrics to SSP endpoint

hub/config/src/main/java/uk/gov/ida/hub/config/ConfigValidCommand.java
There is ConfigValidCommand class which has a separate module and is used for validating config. It has ConfigDataBootstrap class and the class needs PrometheusClientService class and CertificateValidityChecker class to avoid Guice configuration errors.
=> AUTO-125: Fix Guice configuration errors

startup.sh
This commit adds `--parallel` and `--daemon` to the gradle command in startup.sh script to reduce the time it takes to run all tests including integration tests. This change saves 1 minute 2 seconds (39.2%).
Before the change : 2m 38s
After the change  : 1m 36s
=> BAU: Speed up startup.sh script

pre-commit.sh
The startup.sh script needs gradle to complete installDist task before starting Hub components (e.g. Config, SAML Engine, SAML Proxy, SAML SOAP Proxy and Policy).
I have tested pre-commit.sh script and it is working properly.
=> BAU: Fix pre-commit failing to start Hub components

hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/PrometheusMetricsIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigModule.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigValidCommand.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateExpiryDateCheckService.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/OcspCertificateChainValidationService.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/PrometheusClientService.java, hub/config/src/main/java/uk/gov/ida/hub/config/configuration/PrometheusClientServiceConfiguration.java, hub/config/src/main/java/uk/gov/ida/hub/config/data/ConfigDataBootstrap.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/CertificateValidityChecker.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/OCSPCertificateChainValidityChecker.java, hub/config/src/test/java/uk/gov/ida/hub/config/data/ConfigDataBootstrapTest.java
This pull request has three commits.
**First commit**
It decouples PrometheusClientService from ConfigDataBootstrap and makes CertificateExpiryDateCheckService a separate background thread (daemon) managed by DropWizard so that it can handle dynamic config changes. It also adds a timestamp to the certificate expiry date metrics to show whether the metrics are stale or not stale. 
**Second commit**
Currently, Sensu hits Config application's /config/certificates/invalid endpoint every 15 minutes which causes it to perform OCSP checking of RP and MSA certificates and returns a list of invalid certificates. Sensu alerts if there are invalid certificates. The second commit adds OCSP Revocation Status Check to Prometheus Metrics which returns all RP and MSA certificates' OCSP revocation …
=> AUTO-146: Changes to Prometheus Metrics

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/ResponseAction.java
For this Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3571167
When we receive an authn response from an IDP we generate a response
action which is returned to the frontend.
We've had a few users and on the 'failed' page on the frontend. This
will happen if we return a response action of 'OTHER'.
Currently we have no insight into when this happens. This will help.
=> BAU Log IDP response action 'OTHER' created

build.gradle, hub/policy/src/test/java/uk/gov/ida/hub/policy/session/RedisSessionStoreTest.java
Currently, verify-hub has two versions of mockito-core (1.9.6) and (2.23.0) libraries loaded. The old version of mockito-core uses ArgumentMatcher (Abstract class) whereas the new version of mockito-core uses ArgumentMatcher (Interface class). This causes Integrated Development Environment (IDE) to be confused and to throw an error message not letting me to compile in IDE. This commit updates verify-hub to use latest version of verify-saml-libs containing the following changes.
- use latest version of verify-test-utils which uses the latest version of mockito-core (2.23.0)
- remove the old version of mockito-core (1.9.6)
These changes resolve the issue mentioned before.
This commit also updates RedisSessionStoreTest class to use org.mockito.junit.MockitoJUnitRunner instead of …
=> BAU: Update to use latest version of verify-saml-libs library

hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/PrometheusMetricsIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/Message.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateExpiryDateCheckService.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/OcspCertificateChainValidationService.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/PrometheusClientService.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/Certificate.java
Every unique combination of key-value label pairs represents a new time series which can dramatically increase the amount of data stored. We should not use labels to store dimensions with high cardinality (many different label values) such as timestamp or other unbounded sets of values. This commit updates to have pair of metrics (one for expiry date or OCSP revocation status and another one for last updated (timestamp)). The last updated metric is used to indicate whether expiry date metric or OCSP revocation status metric is stale or not. It will be used to alert support team that the metrics are out of date and the team will fix the issue. This commit also adds a serial number to certificate metrics since metadata certificate metrics already have serial numbers.
=> AUTO-146: Move last updated from labels to a separate metric

hub-saml-test-utils/src/main/java/uk/gov/ida/saml/msa/test/outbound/HealthCheckResponseFromMatchingService.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/MatchingServiceHealthCheckIntegrationTests.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/MatchingServiceRequestSenderTest.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/PrometheusMetricsIntegrationTest.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/ConfigStubRule.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/MatchingServiceDetails.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/MsaStubRule.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlEngineStubRule.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SleepyHttpStub.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/PrometheusClient.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/PrometheusClientServiceConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthChecker.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceHealthCheckService.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceHealthCheckTask.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceInfoMetric.java
Currently, Sensu hits SAML SOAP Proxy application's /saml-soap-proxy/matching-service-health-check endpoint every 60 seconds which causes it to make a health-check SOAP request to each MSA and then aggregates all of responses from MSAs together into a single yes/no response to the Sensu check. If the Sensu check comes back as "yes", sensu fires a notification to PagerDuty.
This commits adds Matching Service Health Check Service to check MSAs concurrently and provides two metrics to prometheus metrics. The first metric `verify_saml_soap_proxy_msa_health_status` returns a list of MSA health statuses (healthy and unhealthy). For example,
verify_saml_soap_proxy_msa_health_status{matchingService="http://localhost:63846/attribute-query-request",} 1.0 …
=> AUTO-152: Add Matching Service Health metrics to Prometheus metrics

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasAuthnFailedErrorStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/SessionStartedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCountrySelectedState.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasCountrySelectedStateBuilder.java
- The field type for relayState is Optional but it was being serialized
to `null` when absent
- This meant that when we tried to deserialize it, the Optional was set
to null (since it is a reference type)
- Fix it so that the constructor takes just a String and wraps it in
Optional if it is null
=> AUTO: Fix eIDAS state serialization

build.gradle
It removes a redundant SLF4J binding and fixes security vulnerabilities
in jackson-bind and guava.
=> BAU Bump utils to build 350

hub/config/src/main/java/uk/gov/ida/hub/config/domain/IdentityProviderConfigEntityData.java, hub/config/src/main/java/uk/gov/ida/hub/config/dto/IdpDto.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
When an IDP is temporarily down, show users a warning. Explain that the IDP is temporarily down.
Add support for a `temporarilyUnavailable` flag in the main IDP config. Default the flag to `false`. Expose this flag via the main config API for the frontend to consume.
See https://trello.com/c/ly1m24h4/
=> HUB-42: Communicate to users when IDP is having technical difficulty

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/TestSessionResource.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/AbstractAwaitingCycle3DataStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/AbstractMatchRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasUserAccountCreationRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/UserAccountCreationRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/AbstractAwaitingCycle3DataState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/AbstractUserAccountCreationFailedState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/AwaitingCycle3DataState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/Cycle3DataInputCancelledState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasAwaitingCycle3DataState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasUserAccountCreationFailedState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/MatchingServiceRequestErrorState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/NoMatchState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/NonMatchingJourneySuccessState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/PausedRegistrationState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/UserAccountCreationFailedState.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/Cycle3DataInputCancelledStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasAwaitingCycle3DataStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasUserAccountCreationFailedStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/MatchingServiceRequestErrorStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/NoMatchStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/NoMatchStateBuilderTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/PausedRegistrationStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/UserAccountCreationFailedStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasAwaitingCycle3DataStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateControllerTest.java
This pull requests fixes the following states to resolve serialization issues.
* AbstractAwaitingCycle3DataState
* Cycle3DataInputCancelledState
* AbstractUserAccountCreationFailedState
* MatchingServiceRequestErrorState
* NoMatchState
* NonMatchingJourneySuccessState
The field type for relayState is Optional but it was being serialized to `null` when absent. This meant that when we tried to deserialize it, the Optional was set to null (since it is a reference type). This commit fixes it so that the constructor takes just a String and wraps it in Optional if it is null.
=> BAU: Fix state serialization

Dockerfile, build.gradle
- Docker is now responsible for running the whole build on Concourse in
the new pipeline
- Add test and intTest as tasks to run when building images
- Refactored the docker build quite a bit to allow us to eventually use
a base image on Concourse to reduce build times
- Added a task to gradle to allow us to greedily fetch all the
dependencies to take advantage of docker layer caching
=> AUTO-143: Run tests on master

hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyApplication.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/ExceptionAuditor.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxyDuplicateRequestExceptionMapper.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxySamlTransformationErrorExceptionMapper.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxyDuplicateRequestExceptionMapperTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxySamlTransformationErrorExceptionMapperTest.java
Stop treating it as an 'internal server error'. Makes no difference to the front-end, which still displays the same 'something has gone wrong' error to the user.
Co-authored-by: John Watts <john.watts@digital.cabinet-office.gov.uk>
=> dGJgfILT: Change response status on duplicate request exception to 400

build.gradle
1.3.5 was susceptible to a range of CVE's which are fixed by [1.3.9](https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst#v139-feb-24-2019).
One of the dependencies that was bumped by this patch was Apache
HttpClient to v4.5.7 which 4.5.7 introduced an issue where double forward
slashes in URIs would be normalised to just one.
This caused a regression in SAML engine as we use entityIds, which are a
URL, as part of the URL when fetching their encryption keys from config.
This issue is discussed in detail [here](https://issues.apache.org/jira/browse/HTTPCLIENT-1968)
and should be fixed in future (potentially late March or early April).
=> BAU Upgrade dropwizard to 1.3.9

hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/configuration/PolicyConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java
We turn prometheus on in all environments now.  I'd like to remove
this configuration item, but first we have to set the default
behaviour to be enabled so we can remove it from all the config files.
=> enable prometheus by default

hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/CountryMetadataConsumerTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/DenialOfServiceAttacksIntegrationTests.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/SamlMessageReceiverApiResourceTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/SamlMessageSenderApiResourceTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxySamlTransformationErrorExceptionMapper.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/SamlProxySamlTransformationErrorExceptionMapperTest.java
Send back a 400 status code from `saml-proxy` when a `SamlTransformationErrorException` thrown from this service, in preference to a 500 status code.
`frontend` does not currently discriminate between 4xx's and 5xx's, see `lib/api/hub_response_handler.rb:8`
Use of Jersey bean validation on the request DTO was reviewed but not used, as validation is interleaved with base64 decoding and unmarshalling on the /SAML2/SSO/API/RECEIVER resource
A second PR to follow with acceptance tests for invalid payloads.
=> saml-proxy SamlTransformationErrorExceptions back to frontend with 400 status code

hub/config/src/main/java/uk/gov/ida/hub/config/ConfigApplication.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineApplication.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyApplication.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyApplication.java
PR #240 introduced metrics for hub and idp trust stores but missed out
these other ones.
saml-soap-proxy, saml-proxy, saml-engine and config all have "rp"
trust stores.  In addition, config has a "client" trust store - I'm
not sure if this is the best name for it but I don't know what else to
call it.
=> Add trust store metrics for all the trust stores

Dockerfile
The config files in alphagov/verify-infrastructure ([example](https://github.com/alphagov/verify-infrastructure/blob/master/terraform/modules/hub/files/tasks/hub-policy.json)) expect config files with the name of the application.
This PR introduces that behaviour.
Also `bin/policy server config.yml` confuses me in the context of `bin/config server config.yml`
=> Put cfg files where verify-infrastructure expects

configuration/config.yml, configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/PrometheusMetricsIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/config/src/test/resources/config.yml, hub/policy/src/main/java/uk/gov/ida/hub/policy/configuration/PolicyConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/test/resources/saml-engine.yml, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/test/resources/saml-proxy.yml, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/PrometheusMetricsIntegrationTest.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
Set prometheus support to be enabled everywhere, and remove this as a configuration item.
Configuration items are only worth keeping if we actually intend to use them.
=> Remove prometheusEnabled config item

configuration/saml-soap-proxy.yml
MSA timeout is 50 seconds whereas MSA healthcheck timeout is 2 seconds. There are 281 timeouts in MSA healthcheck in production over the last 7 days via Kibana. This commit updates the MSA healthcheck timeout to 50 seconds which is same as MSA timeout. This change will reduce the number of timeouts occurred in MSA healthcheck.
=> BAU: Increase MSA healthcheck timeout

configuration/saml-soap-proxy.yml
The keepAlive value determines how long a persistent connection is kept open on the client side without being used (between two http requests). This value must be set less than the server side idleTimeout (defaults to 30 seconds in Dropwizard server) otherwise the connection can be closed on the server’s end resulting a org.apache.http.NoHttpResponseException when the client tries to reuse the connection.
SAML SOAP Proxy MSA client and SAML SOAP Proxy MSA HealthCheck client both have keepAlive set to 60 seconds. MSA server's idleTimeout defaults to 30 seconds. The clients' keepAlive are greater than the server's idleTimeout. There are 5,422 org.apache.http.NoHttpResponseException in SAML SOAP Proxy log file in production over the last 7 days via Kibana. This commit sets the keepAlive to …
=> BAU: Fix keepAlive issue

configuration/saml-soap-proxy.yml, hub/saml-soap-proxy/src/test/resources/saml-soap-proxy.yml
There are few remaining NoHttpResponseException in SAML SOAP Proxy log file coming from SAML Engine only (for generating attribute query requests). This commit updates httpClient keepAlive to 10 seconds instead of 60 seconds to eliminate these exceptions. This commit also updates clients' keepAlive to 10 seconds in SAML SOAP Proxy configuration file used for unit testing and integration testing.
=> BAU: Fix remaining keepAlive issue in SAML SOAP Proxy

build.gradle, hub-saml-test-utils/build.gradle, hub-saml/build.gradle, hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/EidasAttributesLogger.java, hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/decorators/SamlAttributeQueryAssertionSignatureSigner.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/domain/EidasAttributesLoggerTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorService.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/IdpAuthnResponseTranslatorServiceTest.java
The hash of user attributes logged by saml engine gets compared with a
hash of user attributes in the proxy node. The PID used to produce this
hash in the proxy node has already itself been hashed by the VSP so we
need to replicate this behaviour in the EidasAttributesLogger.
Note: this also updates the hub to the latest and greatest singular Verify SAML library.
=> EID-1362: Use hashed PID for eIDAS logging

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/SessionRepository.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/exception/UnexpectedAuthnResponseException.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromIdpService.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/SessionRepositoryTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromIdpServiceTest.java
Where the session state is one that includes information on the IDP, decrypt the request and record the request details in the error created. Add tests for new function, and check that the old behaviour still works. Raises new exception whose message will get passed through to the frontend.
See https://trello.com/c/GVzYvzsG/104-understand-and-fix-invalidstate-errors
=> GVzYvzsG: add response details on invalid session state

hub/policy/src/main/java/uk/gov/ida/hub/policy/exception/UnexpectedAuthnResponseException.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromIdpService.java
UnexpectedAuthnResponseException now extends InvalidSessionStateException so that it gets caught by the correct mapper.
=> BAU: add new exception to mapper

configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, hub/policy/src/test/resources/policy-with-redis.yml, hub/policy/src/test/resources/policy.yml, hub/saml-engine/src/test/resources/saml-engine.yml, hub/saml-proxy/src/test/resources/saml-proxy.yml
The keepAlive value determines how long a persistent connection is kept open on the client side without being used (between two http requests). This value must be set less than the server side idleTimeout (defaults to 30 seconds in Dropwizard server) otherwise the connection can be closed on the server’s end resulting a org.apache.http.NoHttpResponseException when the client tries to reuse the connection.
SAML SOAP Proxy HTTP client, SAML SOAP Proxy MSA client and SAML SOAP Proxy MSA HealthCheck client had keepAlive set to 60 seconds. SAML Engine server's and MSA server's idleTimeout defaulted to 30 seconds. The clients' keepAlive were greater than the servers' idleTimeout. There were 5,422 org.apache.http.NoHttpResponseException in SAML SOAP Proxy log file in production over the last 7 …
=> AUTO-340: Update keepAlive on remaining applications for consistency

.travis.yml
- We run Java11 in prod, so there's no reason we need to be backwards compatible
- This will save time with the travis builds
=> bau - dont build using travis with java8

idea.gradle
Pre-requisite for starting to use Java 9+ features
=> BAU: use Java 11 in IntelliJ

hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/EidasAttributesLogger.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/domain/EidasAttributesLoggerTest.java
We need to log a hash of user attributes in both the Hub and Proxy Node for security reasons.
In order to compare these hashes, we need to join two log events on some key, in this case a hub request id.
Proxy Node uses the request id generated by the `VSP` as its "hub request id".
When processing the SAML Response from the IDP, the equivalent id is the "inResponseTo" attribute value sent back by the IDP.
This PR will update the key to use the "inResponseTo" attribute value.
Note that this logging is only activated on a Hub journey originating from our eIDAS Proxy Node.
=> eidas logging: use inResponseTo from IDP as hub request id

build.gradle
This bumps the event emitter's dropwizard-logstash dependency to 1.3.9-71.
This was committed earlier this month but didn't get deployed.  We want to deploy a new version of the event emitter now, so we'd like to see this older one deployed first.
=> BAU: Bump event emitter to 0.0.1-59

build.gradle
https://trello.com/c/y8ieTzSO/14-adjust-event-emitter-to-log-encrypted-event
=> Bump event emitter to 0.0.1-60

build.gradle
We want to standardise Hub compile and runtimes to OpenJDK 11.
This PR will allow Hub to depend on the latest `verify-saml-libs`, compiled with with OpenJDK 11.
=> use latest verify-saml-libs in Hub, built with OpenJDK 11

hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
MSA errors should come back with stack traces. By logging them at an `info` level, they are not being surfaced clearly in monitoring tools. The errors that are thrown as a result don't have the MSA stack trace so it is not always clear what the problem was. This should help.
[Trello card](https://trello.com/c/PwUqib5x/85-improve-hub-re-logging-of-msa-errors)
=> Trello: PwUqib5x: Increase MSA SOAP response error log level

build.gradle, configuration/saml-engine.yml, hub/saml-engine/build.gradle, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/SplunkLoggerTest.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineApplication.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/SplunkAppenderFactory.java, hub/saml-engine/src/main/resources/META-INF/services/io.dropwizard.logging.AppenderFactory, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/logging/SplunkAppenderFactoryTest.java, hub/saml-engine/src/test/resources/saml-engine.yml
**Not to be merged until urls, tokens, sources and sourceTypes are received from cyber, and made available from parameter store.**
This is based on @andy-paine's PR to add the SplunkAppenderFactory
It adds the splunk appender to the `EidasResponseAttributesHashLogger` logger so that the logs are send to splunk. From there cyber can compare them to the hashed attribute logs that they're already receiving from the proxy-node.
Closes #249
=> Eid 1422 Send saml engine hash attribute logs to splunk

hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
Reverts alphagov/verify-hub#269
It is generating too much noise. We will revisit once MSA logging improvements are made.
=> Revert "Trello: PwUqib5x: Increase MSA SOAP response error log level"

configuration/saml-engine.yml
The splunk sourceType and index are remaining static across all the
environments, which means we can just add them to the config rather than
inject them in as env variables.
This also changes the sourceType we're using as they can only contain
[a-z0-9_]. This one is provided by cyber.
=> EID-1422 Hard code splunk config

hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
The variable named "stack trace" can be anything: it is the body of the response from the MSA. So the logs shouldn't explicitly name it as a stack trace as this can be misleading.
=> BAU: remove misleading reference to stack trace

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/SplunkAppenderFactory.java
The logger won't be seeing huge traffic and this makes debugging
easier.
=> EID-1422 Reduce Splunk appender batch size to 1

hub/config/src/main/java/uk/gov/ida/hub/config/ConfigConfiguration.java, hub/config/src/main/java/uk/gov/ida/hub/config/configuration/SelfServiceConfig.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/TransactionConfig.java
* Added self service section to the configuration of the config service
itself to configure enabling self service globaly and provide the source
URL that the self service data will be availible from.
* Added selfService option to the transaction config, so enable self
service for that service.
=> l4zBlwLF: Add config options for self SelfServiceConfig

hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateExpiryDateCheckService.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateService.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/OcspCertificateChainValidationService.java, hub/config/src/main/java/uk/gov/ida/hub/config/data/ConfigRepository.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/CertificatesResource.java, hub/config/src/test/java/uk/gov/ida/hub/config/application/CertificateServiceTest.java
The existing CertificateService was difficult to understand. This refactor simplifies the code so we can build out the functionality to retrieve certificates from remote repositories.
=> l4zBlwLF: Refactor CertificateService for clarity

build.gradle
The latest (`192`) build of `verify-saml-libs` is compiled using OpenJDK-11, but with a java 8 compile target.
This makes the library compatible with dependents like `verify-matching-service-adapter`, which might be compiled with Java 8.
Although `Hub` is now compiled against Java 11, this PR bumps the version of `verify-saml-libs` to track the latest release of `verify-saml-libs`.
This PR follow on from alphagov/verify-saml-libs#63
=> use latest verify-saml-libs compiled with java 8 compile target

build.gradle, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/SplunkLoggerProxyTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/SplunkAppenderFactory.java
We've forked Splunk's java logging library so that we can add the
ability to configure the proxy to use. The library uses an Apache http
client under the hood, and it doesn't use the java system properties by
default like the Jersey clients the apps use. The library offers no way
to configure the proxy; this is what was added by our fork. Hopefully we
can get the changes merged upstream.
=> EID-1422 Use Verify's fork of Splunk logging library

hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/PrometheusMetricsIntegrationTest.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceHealthCheckTask.java
Ensure that MSAs that have been unhealthy for a long time still appear on the Grafana dashboard. Some info fields will be empty (e.g. version), but that's probably better than nothing.
See https://govuk.zendesk.com/agent/tickets/3679369
=> ZD3679369: record unhealthy MSA info

pre-commit.sh
In response to an incident, we're adding a check to our pre-commit scripts
to ensure no AWS credentials are being committed. It's using the AWS-provided
`git secrets` script - https://github.com/awslabs/git-secrets
=> BAU: Check for AWS credentials being committed

hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/MatchingServiceHealthCheckIntegrationTests.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/PrometheusMetricsIntegrationTest.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/MsaStubRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/HealthCheckSoapRequestClient.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/MatchingServiceHealthCheckClient.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/domain/MatchingServiceHealthCheckResponseDto.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthChecker.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/rest/HealthCheckResponse.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceHealthCheckService.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/builders/HealthCheckResponseBuilder.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/builders/MatchingServiceHealthCheckerResponseDtoBuilder.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/client/MatchingServiceHealthCheckClientTest.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthCheckerTest.java
All live MSAs report their version and other information through the `responseId` mechanism. The code to look for the version number in the HTTP headers is now redundant and has been cleaned out.
=> Clean out old healthcheck version mechanism

build.gradle, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/factories/EidasValidatorFactory.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/ResponseAssertionsFromCountryValidator.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/ResponseAssertionsFromCountryValidatorTest.java
This pulls in build 193 of saml-lib. The new version allows unsigned
assertions from eIDAS countries. The eIDAS SAML profile allows this,
whereas the Verify profile does not.
=> EID-1504 Allow unsigned eIDAS assertions

hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/AttributeQueryRequestClient.java
MSA logs don't contain a lot of useful information. It's hard to use them to identify what a problem is.
We should implement error logging changes to the MSA so that the full stacktrace is returned to the Verify Hub when an HTTP 500 error happens in the MSA.
There is some further background in Anshul's [investigation into MSA 500 errors](https://docs.google.com/document/d/10-oAqzKiPXu4nzwD9GL7knABwKxOLNY4oUlo6gC4uRA/edit#).
Original Zendesk ticket:
https://govuk.zendesk.com/agent/tickets/3651026
Change special exception handling to look for exception name at start of message, as message will potentially now contain full stack trace rather than just contain the exception name.
https://github.com/alphagov/verify-matching-service-adapter/pull/122
=> N7edPMiO: Improve MSA Logging

hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/providers/DecoratedSamlResponseToIdaResponseIssuedByIdpTransformer.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/providers/DecoratedSamlResponseToIdaResponseIssuedByIdpTransformerTest.java
If a user is on a **Proxy Node** journey through the Hub, and via the IDP, lands up in one of these states:
- No Authn Context Event
- Authn Failure
- Submit Requester Error
- Submit Fraud Event
then they are presently shown a frontend "_Sorry, something went wrong_" page.
If the user was **not** on a Proxy Node journey then the above scenario would result in the user seeing the "{IDP} couldn’t sign you in" page.
Users in a Proxy Node journey through the Hub **should not** see a different error page for the error events above.
The **Proxy Node** journey through the Hub additionally logs a hash of eidas user attributes, and this evaluation is causing an error in `saml-engine`, and the "_Sorry, something went wrong_" page is then shown.
This PR updates the logic used to decide whether to …
=> EID-1517: Only log user attributes in a Proxy Node journey when matching dataset is present

hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateService.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/CertificateConfigurable.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/MatchingServiceConfig.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/TransactionConfig.java
Everything that implements `CertificateConfigurable` also implements
`EntityIdentifiable`. In `CertificateService` we had a generic type
definition that required both implementations. We can simplify this by
having `CertificateConfigurable` extend `EntityIdentifiable`.
=> l4zBlwLF: Simplify generics for CertificateService

build.gradle, hub/config/build.gradle, hub/policy/src/main/java/uk/gov/ida/hub/policy/configuration/EventEmitterConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/EventEmitterConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/EventEmitterConfiguration.java
- The latest version of verify-event-emitter includes the ability to send audit messages directly to an SQS queue for DCS.
- The only impact on hub is the need to add a SourceQueueName property to the Event Emitter config.  This is an optional field and will be blank for hub which uses the API Gateway Event Emitter.
- aws-java-sdk-s3 was provided transitively via verify-event-emitter.  As S3 is not used in this library it has been removed from the list of jars.  The library is now included as a direct verify-hub dependency instead.
- verify-utils-libs library itself and the version in Hub has also been updated as this library depends on verify-event-emitter.
=> OGD-138: Integrate verify-event-emitter library updated with SQS.

hub/config/src/test/java/uk/gov/ida/hub/config/data/S3ConfigSourceTest.java
Test is failing because the async thread is taking to long in CI. Temporarily increasing sleep time. Will rethink the testing if this.
=> l4zBlwLF: Give test more time

build.gradle
verify-saml-libs were altered so that a duplicate assertion is logged as a warning instead of an error.
Alter build.gradle so that the updated verify-saml-libs are used by the hub.
=> ZD-3570817 matching dataset duplication error

hub-saml-test-utils/build.gradle, hub-saml/build.gradle
This change updates Gradle files to publish hub-saml and hub-saml-test-urils libraries to Artifactory externally instead of locally. This change is needed for jobs in Concourse to publish the libraries to Artifactory externally.
=> AUTO-112: Pubish libraries to Artifactory externally

build.gradle
This change changes from wiremock to wiremock-standalone to avoid Jetty incompatible issues encountered in Verify Test RP's integration tests. Please see https://github.com/tomakehurst/wiremock/issues/551 for further details. This change also upgrades wiremock-standalone to the latest version for consistency (verify-saml-libs has this library).
I ran pre-commit script and it passed all unit tests and integration tests.
=> AUTO-112: Update Wiremock library

build.gradle, hub/config/build.gradle, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/SelfServiceIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigIntegrationApplication.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigApplication.java, hub/config/src/main/java/uk/gov/ida/hub/config/ConfigModule.java, hub/config/src/main/java/uk/gov/ida/hub/config/configuration/SelfServiceConfig.java, hub/config/src/main/java/uk/gov/ida/hub/config/data/S3ConfigSource.java
This commit adds and and wires up Adobe's S3Mock for integration tests.
At this stage the `SelfServiceIntegrationTest` does not exercise code
that performs S3Integration, just wires up the mock AmazonS3 client
object so that it is availible. The next step is to add the code that
merges local and remote config and extend the integration test to
exercise that.
=> L4zBlwLF:  S3 integration test

configuration/config.yml
Set the other required configuration for the config service to read the new metadata bucket.
Corresponding PRs:
https://github.com/alphagov/verify-infrastructure-config/pull/158
https://github.com/alphagov/verify-infrastructure/pull/244
https://trello.com/c/glz5vLuk/485-update-the-config-in-hub-to-enable-the-e2e-journey
=> Parse Self Service enabled config

hub/config/src/main/java/uk/gov/ida/hub/config/data/S3ConfigSource.java
When we don't have access to the amazon resource we get an exception when getting the object. This was not being caught correctly. This PR resolves that.
=> l4zBlwLF: Fix exception  handling

hub/config/src/main/java/uk/gov/ida/hub/config/data/S3ConfigSource.java
In the event of a there being a problem with the initial cache load, we
should populate the cache with the default empty `RemoteConfigCollection`.
=> BAU: Ensure cache load

hub/config/src/main/java/uk/gov/ida/hub/config/ConfigApplication.java
Trying to work out why we can't connect to S3. Trying with an explicity
set region when building he client. If this works we will move this into
self service config.
=> BAU: Initialise S3 client with region

build.gradle, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/config/ConfigServiceKeyStore.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/config/TrustStoreForCertificateProvider.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/config/ConfigServiceKeyStoreTest.java
We want to be able to turn off validating certificate chains with our
root trust store for RPs (and their MSAs). We have previously added an
`enabled` flag to the `ClientTrustStoreConfiguration` in
`verify-utils-libs`.
This commit:
Updates `TrustStoreForCertificateProvider` to return `Optional<KeyStore>`
from `getTrustStoreFor`.
Uses the new `enabled` flag in `ClientTrustStoreConfiguration` to
determine whether or not to return the configured trust store.
Updates `ConfigServiceKeyStore` to validate using the trust store only
if it is present. i.e. the Optional returned from `getTrustStoreFor` is
not empty.
co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov>
=> xHGobHw4: Use enabled flag in TrustStore Config

build.gradle, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ProtectiveMonitoringLogFormatterTest.java
Bump the version of libs from verify-saml-libs that we use.
Fix a test that was dependent on a string value from the bumped libs.
=> BAU: Bump saml-lib version

build.gradle, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/factories/EidasValidatorFactory.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/ResponseAssertionsFromCountryValidator.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/ResponseAssertionsFromCountryValidatorTest.java
There was an issue with how this was implemented and it needs rolling
back. This reverts the code and pulls in an updated version of saml-libs
that no longer contains the issue.
This feature will be reimplemented in future with a different approach.
=> EID-1583 Revert eIDAS insigned assertions handling

hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/UserAccountCreationAttribute.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/SamlEngineStubRule.java
We can remove the use of guava in `UserAccountCreationAttribute` by using `Stream`s more effectively.
By adding a helper method to `SamlEngineStubRule` we can make the `Stream`s invocation a bit neater
=> Make better use of the Streams API

hub/config/src/main/java/uk/gov/ida/hub/config/data/S3ConfigSource.java, hub/config/src/test/java/uk/gov/ida/hub/config/data/S3ConfigSourceTest.java
This class can be simpler.
* We don't need the whole of `SelfServiceConfig`, just the key name for the object in S3
* Merge both copies of the code for pulling objects from S3
=> Make S3ConfigSource simpler

hub/config/src/main/java/uk/gov/ida/hub/config/domain/remoteconfig/RemoteConfigCollection.java
The logging framework uses `{}` for format placeholders rather than `%s`
=> Use correct format placeholders in RemoteConfigCollection

hub-saml/src/main/java/uk/gov/ida/saml/metadata/domain/HubIdentityProviderMetadataDto.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/CertificatesResourceIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/MatchingServiceResourceIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/PrometheusMetricsIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/SelfServiceCertificatesResourceIntegrationTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateService.java, hub/config/src/main/java/uk/gov/ida/hub/config/data/LevelsOfAssuranceConfigValidator.java, hub/config/src/test/java/uk/gov/ida/hub/config/data/LevelsOfAssuranceConfigValidatorTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/exceptions/ConfigValidationExceptionTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRuleWithRedis.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/validators/LevelOfAssuranceValidator.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/exception/StateProcessingValidationExceptionMapperTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/CountriesServiceTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/validators/LevelOfAssuranceValidatorTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/EidasDisabledResourceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/IdpAuthnRequestGeneratorResourceTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/IdaAuthnRequestTranslatorTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/handlers/HubAsIdpMetadataHandler.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/healthcheck/MatchingServiceHealthCheckHandlerTest.java
Make use of `singletonList()` where we can
Stop passing sizes to `toArray()` where we don't need to
Simplify `CertificateService` by removing the unused `getAllCertificates` method and make use of the constructor to `ArrayList` which takes a `List` in `getAllCertificates`
=> Simplify our handing of arrays in various places

hub/config/src/main/java/uk/gov/ida/hub/config/data/ManagedEntityConfigRepository.java, hub/config/src/test/java/uk/gov/ida/hub/config/data/ManagedEntityConfigRepositoryTest.java
Certificates overridden by remote config need to be flagged as such. This was actually done in 8HRTuUnq. These are tests that were not included there.
Also a little refactor to the the override code to make it a little cleaner.
=> ErCu45oA: Test CertificateOrigin on overridden

hub-saml/src/test/java/uk/gov/ida/saml/core/security/RelayStateValidatorTest.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/authnrequest/AuthnRequestFromTransactionValidatorTest.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/authnrequest/AuthnRequestIssueInstantValidatorTest.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/validators/authnrequest/DuplicateAuthnRequestValidatorTest.java, hub-saml/src/test/java/uk/gov/ida/saml/metadata/transformers/decorators/SamlEntityDescriptorValidatorTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/PrometheusMetricsIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/data/ConfigDataBootstrap.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/ConfigStubRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java
Replace some anonymous types with lambdas and use method references instead of lambdas where we can
=> Simplify lambda usages

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/logging/UnknownMethodAlgorithmLogger.java
We don't need the static initialiser here now that we can do `Set.of(...)`
Also, by passing `Signature` objects around a bit more, we can reduce some boilerplate and remove an `Optional` at the same time as making better use of the `Optional`s we have
=> Simplify UnknownMethodAlgorithmLogger

hub-saml/src/main/java/uk/gov/ida/saml/hub/domain/UserAccountCreationAttribute.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/UserAccountCreationAttribute.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/UserAccountCreationAttribute.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/controllogic/SamlMessageType.java
Remove an unnecessary `Integer.toString()` and also `private` modifies for enums, which are superfluous
Co-Authored-By: IntelliJ
=> Two small cleanups

hub/config/src/test/java/uk/gov/ida/hub/config/application/OcspCertificateChainValidationServiceTest.java
* Checks that gauges are updated based on cert chain validity.
https://trello.com/c/s4ekDNZR/558-ocspcertificatechainvalidationservice-should-use-certificates-validation-flag-to-determine-validation-method
=> s4ekDNZR: Unit test for OcspCertificateChainValidationService

configuration/saml-proxy.yml
We need to turn off cert chain validation on staging, which we will do by disabling the RP truststore there.
https://trello.com/c/5CR1WpE4/627-verify-the-e2e-journey-with-self-signed-certs
=> 5CR1WpE4: RP truststore flag for saml-proxy

configuration/saml-engine.yml
We need to turn off cert chain validation on staging, which we will do by disabling the RP truststore there.
=> 5CR1WpE4: RP truststore flag for saml-engine

configuration/saml-soap-proxy.yml
We need to turn off cert chain validation on staging, which we will do by disabling the RP truststore there.
=> 5CR1WpE4: RP truststore flag for saml-soap-proxy

hub-saml/src/test/java/uk/gov/ida/saml/hub/domain/EidasAttributesLoggerTest.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/IdaResponseFromIdpUnmarshallerTest.java, hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/support/ConfigAppRule.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/filters/IdpPredicateFactoryTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRuleWithRedis.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/logging/ExternalCommunicationEventLoggerTest.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/PrometheusMetricsIntegrationTest.java, hub/saml-soap-proxy/src/test/java/uk/gov/ida/hub/samlsoapproxy/logging/ExternalCommunicationEventLoggerTest.java
Now we have Java 9, we can make use of Java's built-in immutable collection
support.
=> Remove more guava from tests

hub-saml/src/test/java/uk/gov/ida/saml/metadata/IdpMetadataPublicKeyStoreTest.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/CountryMetadataRule.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/NodeMetadataFactory.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java
We can just re-throw a RuntimeException here. Code quality tools won't like it,
but it's going to be good enough to fail a test.
=> Remove guava `Throwables` from tests

hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/serialization/StateJsonSerializationTest.java
Policy now uses Redis and serializes `State` data using JSON. We need to check that we don't make changes to the JSON serialization accidentally. Changes to the serialization that are unintended could cause ZDD problems during deserialization.
These tests check that the we are serializing to the current known format.
=> Test JSON Serialization for Redis

hub-saml-test-utils/build.gradle, hub-saml/build.gradle
hub-saml and hub-saml-test-utils are currently consumed by the
verify-service-provider (VSP). The VSP supports Java 8 and needs these
libraries to be compatible. Currently they're built with Java 11.
=> EID-1605 Set hub-saml and hub-saml-test-utils to 1.8

hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToIdpIdaStatusMappingsFactory.java
We have a theory that AuthenticationFailed statuses are not being mapped
correctly. If an IDP returns anything for status detail, the status
won't be matched. As this is the only status with a status of Responder
and a sub-status of Authn_failed, we shouldn't care too much about the
detail value.
=> BAU Add logging to check status mapping logic

hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/inbound/SamlStatusToIdpIdaStatusMappingsFactory.java, hub-saml/src/test/java/uk/gov/ida/saml/hub/transformers/inbound/IdpIdaStatusUnmarshallerTest.java, hub-saml/src/test/resources/status-authnfailed-with-detail.xml
My knowledge of status's and the significance of details within them is
low is feedback on this is appreciated.
We've recently seen an increase in errors being thrown when an IDP
returns an AuthenticationFailed status. This is due to a [recent change
in the logic for mapping the status from the SAML to a Java object](https://github.com/alphagov/verify-hub/pull/369).
This status has a top-level status of Responder and a sub-status of
Authn_failed. The recent changes meant that we failed to match this
status when mapping if the IDP also included a status detail value (we
_only_ matched if there was no detail).
We added some logging to check if IDP's were including detail values for
this status and it turns out they were. [An example can be seen …
=> BAU Don't check detail for AuthenticationFailed status

build.gradle
This is mainly a bump to upstream transitive dependencies, such as to
prometheus:client_java 0.7.0.
=> bump to latest gds-metrics-dropwizard

hub-saml-test-utils/build.gradle, hub-saml/build.gradle
We should not be building with a target of 1.8. We have code that requires 11. Target of 1.8 was added to enable compatibility with the VSP, however the VSP's dependency on this project was removed.
=> BAU: Revert change that made code target JDK 1.8

hub-saml/src/main/java/uk/gov/ida/saml/core/domain/CountrySignedResponseContainer.java, hub/policy/build.gradle, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasMatchingServiceResourceIntegrationTest.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/EidasSessionResourceIntegrationTest.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/InboundResponseFromCountry.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryServiceTest.java
Microservices in the Hub need a common data transfer object (DTO) to hold data when an eIDAS SAML Response has unsigned assertions. This DTO is the `CountrySignedResponseContainer`.
This data in it is:
- base64 of original eIDAS SAML Response
- list of encrypted secret keys a Government Service can decrypt and then use to decrypt the encrypted eIDAS assertion
- the country entityId in order to set an Assertion Issuer
This PR introduces the DTO to the Hub codebase, and adds it as an optional parameter to the `InboundResponseFromCountry`, which will be used in both the MSA and VSP journeys.
=> DTO to represent data required to process unsigned assertions in an eIDAS SAML response

build.gradle
Builds of `hub-saml` were failing in some environments when the build target was java 11. This was due to an old version of mockito that was not compatible with java 11 in some circumstances.
We are transitively dependant on Mockito via Junit 4, but we are already on the latest version of the 4 branch.
Forced upgraded to latest mockito 2.xx.xx version.
=> BAU: Update Mockito version

hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/client/PrometheusClient.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/PrometheusClientServiceConfiguration.java
Creating a large number of threads will require a large memory. This change also makes the following three thread pool settings configurable. This allows us to change the settings using SAML SOAP Proxy's configuration file instead of changing its code.
1. Minimum number of threads (defaults to 0)
2. Maximum number of threads (defaults to 50)
3. Keep alive time (defaults to 60 seconds)
=> BAU: Limit the maximum number of threads to 50 for Prometheus client

hub/config/src/main/java/uk/gov/ida/hub/config/domain/TransactionConfig.java
All services services should be using SHA256. This changes the default.
=> BAU Set shouldSignWithSHA1 default to false

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/TestSessionResource.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasAwaitingCycle3DataStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasAwaitingCycle3DataState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCycle0And1MatchRequestSentState.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/state/EidasCycle3MatchRequestSentState.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasAwaitingCycle3DataStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasCycle0And1MatchRequestSentStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/builder/state/EidasCycle3MatchRequestSentStateBuilder.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasAwaitingCycle3DataStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/serialization/StateJsonSerializationTest.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/builders/ResponseBuilder.java
CountrySignedResponseContainer is now passed back in the various matching cycle states unless it's not present in which case an Optional.empty() is returned. This allows the original SAML Country Response to be sent with the Cycle3 data if required.
Co-authored by: Chris Wynne <christopher.wynne@digital.cabinet.office.gov.uk>
=> Eid 1714 pass country resposne data to cycle3 attribute query

hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/IdentityProviderResourceIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/IdentityProviderConfig.java, hub/config/src/main/java/uk/gov/ida/hub/config/domain/filters/OnboardingIdpPredicate.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/IdentityProviderConfigTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/domain/builders/IdentityProviderConfigDataBuilder.java
Clean up `IdentityProviderConfig` by removing `onboardingTransactionEntityIdsTemp`.
This looks like it should have been removed a loooong time ago, but was just crufting up the code.
=> BAU: Clean up the IDP Config

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle3MatchRequestSentStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasMatchRequestSentStateController.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle0And1MatchRequestSentStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCycle3MatchRequestSentStateControllerTest.java
When the MSA doesn't find a user we enter the user account creation flow. In the case of unsigned assertions, we need to send the data from the `countrySignedResponseContainer` object as an assertion in the attribute query, rather than the original encrypted assertion.
Work has already been done to ensure that this object is available in the correct states, as well as the work to include the unsigned response assertion rather than the encrypted assertion (in `HubEidasAttributeQueryRequestToSamlAttributeQueryTransformer`).
=> EID-1721 Pass countrySignedResponseContainer to MSA for user account creation

hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
These deprecated endpoints should no longer be in use. Double check that by logging any access with a warning.
=> BAU: Log access to deprecated endpoints

hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateService.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/CertificatesResource.java, hub/config/src/test/java/uk/gov/ida/hub/config/application/CertificateServiceTest.java, hub/config/src/test/java/uk/gov/ida/hub/config/application/OcspCertificateChainValidationServiceTest.java
CertificateService did not need to declare generic types. Refactored to remove them.
This was driven by Jersey logging warnings that a concrete type for CertificateService could not be found. This seems to an issue with Jersey and didn't cause any real problems, but simplifying the generics here resolved the issue anyway.
=> BAU: Simplify use of generics

Dockerfile
After OpenJDK JRE v11.0.4 got upgraded to OpenJDK JRE v11.0.5 on 21st October 2019, Policy and SAML Proxy applications started using more memory over time. They became unresponsive when they hit their maximum heap memory sizes. Config, SAML SOAP Proxy and SAML Engine applications were not affected.
This commit downgrades OpenJDK JRE from v11.0.5 to v11.0.4 to stop Policy and SAML Proxy from becoming unresponsive for the time being. Policy and SAML Proxy will need to start managing the number of objects they store in their heap memory (e.g. once a user session is completed either successfully or unsuccessfully, the session information can be safely dropped from the heap memory to free up its space for a new user session). 
Task Memory Utilisation Graph …
=> BAU: Pin OpenJDK JRE to 11.0.4

build.gradle
See this PR for the changes being brought in: https://github.com/alphagov/verify-saml-libs/pull/101
It fixes a bug with retrieving decryption keys from encrypted
assertions, when dealing with unsigned assertions.
=> EID-1763 Bump SAML lib to 227

hub/config/src/main/java/uk/gov/ida/hub/config/data/S3ConfigSource.java
We're logging a warn message when the S3 object is null. However, it will be null
most of the time since we only retrieve the object if it has changed.
The local cache expires every 30s by default, but the S3 file will not change that often.
This adds a condition to not log the message when it's happening during the reload phase
and we do not expect the full object to be retrieved.
=> BAU: Decrease the logging noise

Dockerfile, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
Gradle are decommissioning HTTP for Gradle services - see here for more
info: https://blog.gradle.org/decommissioning-http
A knock on effect of this is that if you're using an older version of
the JDK then there's a bug that'll kick a `peer not authenticated` error
when pulling dependencies.
This newer version of Gradle uses JDK 11.0.4. I didn't want to go beyond
this as we've seen issues in the hub with memory leaks when using 11.0.5
and are currently pinned at version 11.0.4, so this matches.
=> Bau upgrade gradle base image

configuration/local/saml-engine.yml, configuration/local/saml-proxy.yml, configuration/local/saml-soap-proxy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/SamlEngineAppRule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/config/CertificatesConfigProxy.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/support/SamlProxyAppRule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyConfiguration.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/SamlProxyModule.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/config/CertificatesConfigProxy.java, hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/support/SamlSoapProxyAppRule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyConfiguration.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/SamlSoapProxyModule.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/config/CertificatesConfigProxy.java
https://trello.com/c/6n6H8nhi/776-make-cache-expiry-for-certs-configurable-in-saml-engine-saml-soap-proxy-and-saml-proxy
Three of the Hub services (saml-proxy, saml-soap-proxy and saml-engine) read federation certs from the config service, and store them in a cache.  The cache was formerly hard-coded to have an expiry time of five minutes.  The self-service cert rotation app needs to wait for this cache to expire in some circumstances, so we want to reduce it to a shorter interval.  We'd prefer for it to be configurable rather than hard-coded (in particular, this should help facilitate testing).
The cache expiry time is set to one minute in the config files.
https://trello.com/c/6n6H8nhi/776-make-cache-expiry-for-certs-configurable-in-saml-engine-saml-soap-proxy-and-saml-proxy
=> 6n6H8nhi -Make cache expiry for certs configurable

.travis.yml, Dockerfile
Upgrade from openjdk jre `11.0.4` to `11.0.6` for latest security updates.
We previously pinned to 11.04 from 11.0.5, in order to avoid a memory issue.
We have doubled memory so believe this will no longer be an issue.
Eyes will be on memory usage when this propagates.
=> BAU Bump openjdk jre to 11.0.6

configuration/saml-engine.yml
The logger classpath has changed. Update saml-engine config to reflect that.
=> HUB-446: Fix eIDAS response attributes hash logging

build.gradle
To address [CVE-2019-20330](https://github.com/dropwizard/dropwizard/pull/3100)
=> BAU: Upgrade dropwizard to 1.3.18

hub/config/src/main/java/uk/gov/ida/hub/config/application/CertificateExpiryDateCheckService.java
This is due to certificates managed by the Cert Admin tool
we will turn this back from warning to error once addressed by
https://govukverify.atlassian.net/browse/HUB-457
=> BAU: Hide sentry null exceptions due to certificates managed by self service tool

hub-saml-test-utils/build.gradle
hub-saml and hub-saml-test-utils have identical bintray configuration,
which means they're trying to upload to the same package location.
This seems like a bad idea and that hub-saml-test-utils should have a
different name.
=> fix hub-saml-test-utils bintray config

hub-saml-test-utils/build.gradle, hub-saml/build.gradle
Bintray is the source of truth now.
Bintray is made available via whitelisted-repos on artifactory, so we
still pull dependencies down using artifactory, but we only need to
push dependencies to bintray.
=> Stop publishing hub-saml{,-test-utils} to artifactory

hub/config/src/main/java/uk/gov/ida/hub/config/application/OcspCertificateChainValidationService.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceHealthCheckService.java, hub/saml-soap-proxy/src/main/java/uk/gov/ida/hub/samlsoapproxy/service/MatchingServiceHealthCheckTask.java, pre-commit.sh, shutdown.sh
This pull request contains two commits.
1. Since Redis is no longer optional (https://github.com/alphagov/verify-hub/pull/422), pre-commit.sh fails to start policy and saml-engine because Redis service is not running or available. This change updates the script to start Redis service before starting Policy and SAML Engine applications. This will avoid throwing "failed to start" error messages.
2.  This change
- updates "OCSP Certificate Chain Validation Service" to catch exception inside the loop and to provide more details on the exception and certificate if it is available. This is to ensure that the service can continue to set OCSP Certificate Revocation Status metrics for the remaining certificates.
- updates "Matching Service Health Check Service" to provide more details on the …
=> AUT-517: Fix pre-commit script and provide more details on exception

build.gradle, configuration/config.yml, configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
We have been using an old library to integrate DropWizard and Sentry.  Before we fine tune the way Dropwizard and Sentry work together, we're updating to the newer code that Sentry recommends.  Ideally this will solve all of our problems on its own and we won't have to do any further tweaking.  It probably won't but we definitely want to be using this before tweaking.
=> HUB-413 Sentry event grouping is wrong

hub/config/src/main/java/uk/gov/ida/hub/config/domain/IdentityProviderConfig.java, hub/config/src/main/java/uk/gov/ida/hub/config/dto/IdpDto.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
This is so the frontend can decide to hide disconnecting IDPs at an appropriate time to avoid a timing issue where the button to select an IDP get rendered shortly before the cut-off time and the user fails to press is before that cut-off time. In that case the user will see an error for a reason completely outside of their control.
Hiding IDPs disconnecting for registration a short period of time before the cut-off time is a crude solution to this as the Hub will still accept requests for those IDPs until the actual cut-off time. This doesn't eliminate the problem completely but given an appropriate time interval it reduces it greatly as most people are not likely to spend more than a few minutes on the picker.
=> HUB-545: Include the `provide registration until` timestamp in the IDP DTO list from config

hub/config/src/main/java/uk/gov/ida/hub/config/dto/IdpDto.java
This annotation is required for ZDD so old version of this DTO can still be serialised from the new JSON
A new field was added to this class in #436 which will cause ZDD failures during deployment without this flag
=> HUB-545: Ignore unknown JSON properties in IdpDto class

hub/config/src/integration-test/java/uk/gov/ida/integrationtest/hub/config/apprule/IdentityProviderResourceIntegrationTest.java, hub/config/src/main/java/uk/gov/ida/hub/config/Urls.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java
"/idp-list" has been replaced by "/idp-list-for-registration"
Frontend uses the new endpoint now
https://github.com/alphagov/verify-frontend/pull/811/files#diff-6ad916848e4bccb8952d47e01d882085R4
=> HUB-545: Remove config endpoint that's no longer used.

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/resources/translators/CountryAuthnRequestGeneratorResource.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApi.java
It would be useful to know the volume of journeys from the UK connector node to EU country Proxy Nodes, to gauge where support effort might need to be.
These metrics count the requests to and responses from EU Proxy Nodes that we are connected to, grouped by country Proxy Node entity id.
We will use these metrics for Grafana dashes and/or alerts.
Tested locally to ensure references to entity ids are null safe.
Locally `idaAuthnRequestFromHubDto.getIdpEntityId()`
gives `http://localhost:50140/stub-country/ServiceMetadata`
amd `samlResponse.getIssuer().getValue()` gives
`http://localhost:50140/stub-country/ServiceMetadata`.
=> BAU Count requests, responses to EU Proxy Nodes

hub/config/src/main/java/uk/gov/ida/hub/config/data/LevelsOfAssuranceConfigValidator.java, hub/config/src/test/java/uk/gov/ida/hub/config/data/LevelsOfAssuranceConfigValidatorTest.java
- We now have an RP which has LOA2 first in config followed by LOA1. This will change the order in which the LOAs appear in the AuthnRequest so that LOA2 is first in the list. This is to show that the RP prefers LOA2 but will accept LOA1 if a user fails to get LOA2.
- Update the config validator to allow this ordering of LOAs in an RP's transaction config.
=> Allow an RP to have config where LOA2 is followed by LOA1

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/IdpSelector.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/proxy/IdentityProvidersConfigProxy.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectorTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/services/CountriesServiceTest.java
We want IDPs which are enabled for receiving registration requests to be able to handle an Authn Request where the ordering of LOAs in the request is [LOA2, LOA1]. This is so that these IDPs will first attempt to achieve LOA2 for the User but failing that will try for LOA1. When a User is on the IDP in a sign-in journey they can switch to a registration journey, so it’s important that this ordering is used in both instances to ensure the IDP behaviour is consistent.
When a Service is configured with the [LOA2, LOA1] ordering of LOAs and they are sending a request to an IDP which is only configured for sign-in, then we want the request to contain just [LOA2]. This will be sent as a LOA2 request meaning a user who obtained LOA2 on registering can use the service. This will give the service …
=> Only send a [LOA2,LOA1] ordering of LOAs to IDPs that are enabled for registration.

build.gradle, hub/policy/src/main/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandler.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/LevelOfAssurance.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/logging/HubEventLogger.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandlerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java
_Previous branches have attempted to run CI tests from PR 447, even though it is closed. Hopefully this new branch will run its own. Travis confirms that this branch builds and tests green._
This PR is one part of several across Verify to be able to support billing for new special case `LOA2,LOA1/exact` requests. It uses two new details keys for events emitted by the hub.
* Update to latest `verify-event-emitter` library (build 77).
* Emit `minimum`, `maximum`, `preferred` LOAs when recording session events.
* Emit `minimum`, `maximum`, `preferred` and `provided` LOAs when recording success events.
* Update tests to reflect the new fields.
The full set of changes being made is laid out in:
* [ADR 36 billing changes plan](https://docs.google.com/document/d/1hblVU0wquj6Z3-b9V75z6jb1wt3Nnpjh2 …
=> Add new level of assurance fields to event system emissions, v3

build.gradle, hub/policy/src/main/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandler.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/LevelOfAssurance.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/logging/HubEventLogger.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/controllogic/AuthnRequestFromTransactionHandlerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java
This PR is one part of several across Verify to be able to support billing for new special case `LOA2,LOA1/exact` requests. It uses two new details keys for events emitted by the hub.
* Update to latest `verify-event-emitter` library (build 77).
* Emit `minimum`, `maximum`, `preferred` LOAs when recording session events.
* Emit `minimum`, `maximum`, `preferred` and `provided` LOAs when recording success events.
* Update tests to reflect the new fields.
The full set of changes being made is laid out in:
* [ADR 36 billing changes plan](https://docs.google.com/document/d/1hblVU0wquj6Z3-b9V75z6jb1wt3Nnpjh2MNHxNGgTBE/edit?usp=sharing)
For context, please see:
* [ADR 35](https://github.com/alphagov/verify-architecture/blob/master/adr/0035-allow-specified-loa2-services-to-receive-loa1-identities. …
=> [DO NOT MERGE] Add new level of assurance fields to event system emissions

hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/CountryMetadataConsumerTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/DenialOfServiceAttacksIntegrationTests.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/MetadataConsumerTests.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/SamlMessageReceiverApiResourceEidasDisabledTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/SamlMessageReceiverApiResourceEidasEnabledTest.java, hub/saml-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlproxy/apprule/SamlMessageReceiverApiResourceTest.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/contracts/SamlRequestDto.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/domain/SamlAuthnResponseContainerDto.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApi.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/resources/SamlMessageReceiverApiTest.java
**What**
- Add the analytic session id and journey type to the saml proxy dto so it is able to receive them from the frontend before logging them in policy.
- Make the necessary changes to the unit tests.
**Why**
- This is half of the change to ensure we log the analytic session id and journey type when we receive a response from an idp. The other half will be in verify-frontend.
- Currently we log the journey type and analytic session id when we receive a response from a country or IDP. However these attributes are always null. This is because the frontend should be adding these attributes to the response before passing it onto saml proxy.
This will work for IDPs. I'm not sure if we need to log either of these attributes for countries on the response. We're not currently logging an …
=> Make sure the journey type and analytic session ID exist when we log it

build.gradle
[DO NOT MERGE PLS]
Use v. 240 of saml-libs which will log request id instead of pid, see https://github.com/alphagov/verify-saml-libs/pull/114
Its correct that the only change is the saml-libs version.
=> #️⃣EID-1980 log request id, rm pid in eidas hash

configuration/config.yml, configuration/policy.yml, hub/config/src/main/java/uk/gov/ida/hub/config/resources/CertificatesResource.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/CountriesResource.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/IdentityProviderResource.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/MatchingServiceResource.java, hub/config/src/main/java/uk/gov/ida/hub/config/resources/TransactionsResource.java, hub/config/src/test/resources/config.yml
Extend hub session duration to reduce the proportion of people timing out. According to our research, extending the session to 2.5h from the current 90 mins will allow 20.8% of users timing out to complete their journey. We will measure this hypothesis and confirm the impact of the extension once this change has been deployed for a bit.
Details in [HUB-601](https://govukverify.atlassian.net/browse/HUB-601?focusedCommentId=25535&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25535)
Consider alongside alphagov/verify-frontend#872
=> HUB-601: Extend hub session duration

hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateController.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/logging/HubEventLogger.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/EidasCountrySelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/domain/controller/IdpSelectedStateControllerTest.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/logging/HubEventLoggerTest.java
- For entries where we are recording the journey time in the event system we want to ensure the IDP entity ID is being used as well so that the reports will be correctly populated. This will ensure that the conformance tests in the event system will run successfully. 
- The failed events would be useful in the event reports so we want to keep them in there before thinking about if there is any other additional information we want to add.
=> Start recording the IDP entity ID for failed events

hub/policy/src/main/java/uk/gov/ida/hub/policy/metrics/EidasConnectorMetrics.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryService.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/services/SessionService.java, hub/policy/src/test/java/uk/gov/ida/hub/policy/metrics/EidasConnectorMetricsTest.java
Use a single counter to record prometheus metrics on SAML requests and responses to EU Proxy Nodes, and classify the responses we receive.
The counter has the labels `country`, `direction` and `status`. We do not experience much traffic through the Connector Node, so the amount of data collected across all labels should be modest.
These metric will make it easier to create alerts and SLOs on questions like:
* is the OK response ratio acceptable per country
* is the request/response ratio acceptable per country
* are these ratios acceptable across countries
=> 📈 BAU Use a single counter to record connector metrics

build.gradle, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/EidasAttributeStatementAssertionValidator.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/validation/country/ResponseAssertionsFromCountryValidator.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/EidasAttributeStatementAssertionValidatorTest.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/validation/country/ResponseAssertionsFromCountryValidatorTest.java
Given an Assertion AttributeValue missing its QName namespace uri, use the matching namespace uri declared in the parent Response element to build a new QName containing a uri.
A match is considered when the namespace prefix of the Assertion and Response match e.g. they both have value of `eidas-natural`.
The new derived QName is then evaluated against a set of expected AttributeValue QNames.
The parent Response object need to be carried through a series of classes in order to be available on the `EidasAttributeStatementAssertionValidator`.
Review `EidasAttributeStatementAssertionValidator` first, and debug the new unit test on `EidasAttributeStatementAssertionValidatorTest`, which contains an eidas Response in the desired state.
We have an issue validating the qualified name (QName) of …
=> EID-1977 Validation of missing namespace uri on Assertion

hub-saml/src/main/java/uk/gov/ida/saml/hub/transformers/outbound/EidasAuthnRequestFromHubToAuthnRequestTransformer.java
According to the EIDAS specification eIDAS Message Format v1.1-2, section 2.4.1, “eIDAS-Connectors MUST support `isPassive`. The attribute SHOULD be set to “false”.
=> ✅ EID-1977 eIDAS-Connectors MUST support isPassive

configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml, hub/policy/src/main/java/uk/gov/ida/hub/policy/configuration/RedisConfiguration.java
See : https://govukverify.atlassian.net/browse/HUB-613
Redis client's timeout will need to change to something smaller than 30 seconds. The timeout among hub services would be 
Redis client = 20s, saml-engine=24 < policy = 26 < saml-proxy = 28 < frontend = 30secs
MSA is also a bottleneck with maximum timeout of about 13 seconds. It timeout is set at 24 seconds in this PR
also see https://github.com/alphagov/verify-frontend/compare/HUB-613-adjust-timeouts-between-microservices
=> HUB-613: adjust timeouts between Microservices

hub/policy/src/main/java/uk/gov/ida/hub/policy/PolicyModule.java, hub/policy/src/main/java/uk/gov/ida/hub/policy/configuration/RedisConfiguration.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/config/RedisConfiguration.java
According to the Lettuce (Redis Client) documentation, it says
```
All connections inherit a default timeout from their {@link io.lettuce.core.RedisClient} and will throw a {@link io.lettuce.core.RedisException} when non-blocking commands fail to return a result before the timeout expires. The timeout defaults to 60 seconds and may be changed via {@link io.lettuce.core.RedisClient#setDefaultTimeout} or for each individual connection.
```
This change updates Redis client's default timeout from 60 seconds to 30 seconds so that SAML Engine and Policy can send exceptions back to the downstream applications when Redis client times out. Redis client's default timeout is configurable and is set to 20 seconds by default.
=> BAU: Update SAML Engine and Policy Redis's default timeout

configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
Reverts alphagov/verify-hub#461
Appears to have broken the build, not sure how yet.
=> Revert "Swap policy, saml-engine, saml-proxy and saml-soap-proxy to using the new Fargated config service"

configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
Reverts alphagov/verify-hub#463
Looks like the pipeline problem was unrelated to this as it kept failing after the revert. Once that's tidied up let's send this one through.
=> Re-apply "Swap policy, saml-engine, saml-proxy and saml-soap-proxy to using the new Fargated config service"

configuration/policy.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
Similar to #461, where we switched to use config-in-fargate.
=> Use saml-engine in fargate

configuration/policy.yml, configuration/saml-engine.yml
SAML SOAP Proxy is up and running on Fargate. This change updates Policy and SAML Engine to use SAML SOAP Proxy on Fargate instead of SAML SOAP Proxy on EC2 instances.
=> AUT-817: Update to use SAML SOAP Proxy on Fargate

Dockerfile
by default java caches DNS (seperatly from the OS DNS cache) queries indefinitly. this is not a practical default when running in a cloud environment with dynamic addresses of load-balaners/applications/databases.
this changes the default java dns ttl to be 5s, leaving much of the caching up to the OS as is expected.
=> java: set sensible default for java dns cache

hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/PolicyAppRule.java, hub/policy/src/integration-test/java/uk/gov/ida/integrationtest/hub/policy/apprule/support/RedisTestRule.java, hub/saml-engine/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlengine/apprule/support/RedisTestRule.java, pre-commit.sh, shutdown.sh, startup.sh
This change updates embedded Redis server to bind to 127.0.0.1. This will stop Operating System (OS) from throwing 'allow incoming network connections' alerts. It updates startup.sh script to start verify-metadata (required by SAML Engine) before starting SAML Engine. It updates shutdown.sh script to shutdown all applications started by the startup.sh script properly.
I have tested pre-commit.sh, startup.sh and shutdown.sh scripts locally. They are working properly. There are no more "allow incoming network connections" alerts.
=> BAU: Stop throwing 'allow incoming network connections' alerts

configuration/config.yml, configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
This small config change should hopefully allow the hub apps to report their correct sentry environment to sentry.
=> HUB-733 Add environment to sentry config

Dockerfile, configuration/config.yml, configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
If you give Sentry some release information this can tie things up
with git hub to show us additional information about errors and
exceptions.
=> HUB533 Give Sentry the git head sha for versioning

build.gradle
This version includes a fix for a bug where metadata resolvers were not
picking up on changes to a countries trust-anchor.
=> BAU: Upgrade saml-libs to 249

Dockerfile
The ability to supply an image for gradle and jdk to Hub Build. The intent is to supply the [gradle](https://github.com/alphagov/verify-terraform/blob/ee016785f7a9ee3a2f60a95109143b8747100e49/environments/tools/platform/files/pipelines/vendor.yml#L268) and [jdk](https://github.com/alphagov/verify-terraform/blob/ee016785f7a9ee3a2f60a95109143b8747100e49/environments/tools/platform/files/pipelines/vendor.yml#L232) images vendored to our ECR registry. DockerHub images are set by default.
Avoid DockerHub rate limits [we are experiencing](https://cd.gds-reliability.engineering/teams/verify/pipelines/deploy-verify-hub/jobs/build-verify-hub-microservices/builds/195) on pulling gradle and jdk11.
Also see https://github.com/alphagov/verify-infrastructure-config/pull/427 which follows.
=> BAU Provide a registry image ARG to docker build

Dockerfile
Ensure image build args like `REGISTRY_IMAGE_JDK` have "global" scope in a multi-stage build.
This has been tested to work with both:
`docker build -t se --build-arg hub_app=saml-engine .` 
and
`docker build -t se --build-arg hub_app=saml-engine --build-arg REGISTRY_IMAGE_GRADLE=gradle:6.7.0-jdk14 .`
=> BAU Make REGISTRY_IMAGE_JDK a global build arg

Dockerfile
Update the Dockerfile to use Vendored containers in Github Container Registry to avoid issues with Docker Hub Rate limiting.
=> HUB-774 Update the Dockerfile to use GHCR

hub/config/src/main/java/uk/gov/ida/hub/config/exceptions/ExceptionFactory.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/exceptions/NoKeyConfiguredForEntityExceptionMapper.java, hub/saml-proxy/src/test/java/uk/gov/ida/hub/samlproxy/exceptions/NoKeyConfiguredForEntityExceptionMapperTest.java
Rejecting unrecognised `entityId`s is a correct behaviour. It should be logged as a warning, rather than an error.
This change alters logging behaviour for uncaught `NoKeyConfiguredForEntityException`s in `saml-proxy`, and when logging the creation of a `NotFoundException` when there's no data for a given `entityId` in `config`. In both cases, switching down from `ERROR` to `WARN` log entries.
FYI - I do not intend to merge this change until I've checked that cyber don't care. (ie. They _might_ consider unrecognised `entityId`s as some kind of indicator of malicious behaviour, and so they _might_ need to know that we're downgrading those logs from `ERROR` to `WARN`.)
=> BAU - Rejecting unrecognised entityIds should come with a warning

Dockerfile
This hopefully will allow sentry to pick up the newly injected release
information.
=> The end of Sentry release needs to be updated

configuration/config.yml, configuration/policy.yml, configuration/saml-engine.yml, configuration/saml-proxy.yml, configuration/saml-soap-proxy.yml
This should fix the broken release infromation we're seeing in Sentry
=> Fix for broken release information

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/SamlEngineModule.java, hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/services/RpAuthnRequestTranslatorService.java, hub/saml-engine/src/test/java/uk/gov/ida/hub/samlengine/services/RpAuthnRequestTranslatorServiceTest.java
We want to be able to easily see what version of the VSP services are
using.
This takes the version provided in authn requests and provides it to
Prometheus as a gauge.
The metric value of 1.0 is not the interesting part, as is only used as
a vehicle for the labels which describe the entity ID and the version.
It's only provided as metrics must provide a double value.
=> HUB-814: Send VSP version info to Prometheus

run.Dockerfile
This uodates the run.Dockerfile to use the same image as our other Dockerfiles
=> HUB-813 Update run.Dockerfile to use Java 11

hub/saml-soap-proxy/src/integration-test/java/uk/gov/ida/integrationtest/hub/samlsoapproxy/apprule/MatchingServiceRequestSenderTest.java
MatchingServiceRequestSenderTest fails sometimes.  We hypothesise that it's because the stubs used are @ClassRules and so static and so probably in the wrong state when
they get used sometimes for reasons not apparent to us.
Instead of diagnosing the problems properly and identifying where the problem lies, we've changed everything to non-static @Rules in the vain hope that this will fix all of our problems.
If we could reliably make the tests fail then it would be worth doing properly but we can't so we wouldn't know if it was actually fixed anyway.
=> BAU Fix pseudo random failures

build.gradle, pre-commit.sh
We don't seem to be using it anywhere other than the pre-commit.sh
script. We don't use pre-commit anywhere apart from locally.
The version we were using was from the Jenkins plugins repo, which has
now been removed (we no longer use Jenkins). Rather than doing the work
to add the version we want to our artifactory, we'd rather just remove
the plugin.
=> BAU: Remove Ben Maines versions versions plugin

build.gradle, hub-saml-test-utils/build.gradle, hub-saml/build.gradle, publish.gradle
**Pipeline changes here: https://github.com/alphagov/verify-infrastructure-config/pull/539**
Bintray is shutting down. This adds the gradle config to publish to
Sonatype, which is then mirrored to MavenCentral.
This has been run locally and is publishing as expected to Sonatype.
=> HUB-866: Publish to maven central

publish.gradle
Without this SonaType refuses to close the repo and so can't be mirrored
to Maven Central
=> HUB-866: Set description in publishing

publish.gradle
The `proj.description` property was blank. This resulted in the
description not being set in the POM. Sonatype was refusing to close
because of this.
Have published this to Sonatype and confirmed that the description is
now set in the POM.
=> HUB-866: Make sure hub sub projects have a description

Dockerfile
We've added a new gradle file (`publish.gradle`) which is referenced in
the `build.gradle` file. If we don't copy the new file into the image
gradle breaks when being run during the build.
=> HUB-866: Add publish.gradle to Dockerfile

Dockerfile
The publish file needs to be copied through to the next image
=> HUB-866: Copy publish.gradle

Dockerfile, run.Dockerfile
Following the decision to use a paid Docker Hub account in the pipeline we'll need to update all our Docker images again to go back to pulling from Docker Hub instead of from GitHub Container Registry.
I've moved the references back to what they originally were when changed here https://github.com/alphagov/verify-hub/commit/db7f531958f2c65f8c26786cda4de40ca8b47d39
=> [HUB-841] Update Dockerfiles to use Docker Hub

Dockerfile
We saw a memory leak when using 11.0.9, so this may help.
You can check the SHA here: https://hub.docker.com/layers/openjdk/library/openjdk/11.0.11-jre/images/sha256-e12869c3edad94f2c23a40d0fe21b307a1a9177a621c9b902ecfa02897ba93f7?context=explore
Keeps the Dockerfile in line with https://github.com/alphagov/verify-infrastructure-config/pull/571
=> BAU: Pin JRE in Dockerfile to 11.0.11

hub/saml-engine/src/main/java/uk/gov/ida/hub/samlengine/security/AuthnRequestKeyStore.java, hub/saml-proxy/src/main/java/uk/gov/ida/hub/samlproxy/security/AuthnRequestKeyStore.java
[Sentry has reported some NullPointerExceptions](https://sentry.io/organizations/gds-verify/issues/2499432728/?environment=production&project=5494398&query=is%3Aunresolved), which are occuring within a catch block.
These are due to `ApplicationException`s being constructed with a null `ExceptionType`. 
The `ApplicationException` is being created due to a call to the config service, and the [underlying cause seems to be an invalid entityid](https://gds.splunkcloud.com/en-GB/app/search/search?sid=1629878890.37579).
Sentry reports 42 of these events, first occuring after our upgrade to DropWizard 2. 
This PR reverses the evaluation of ExceptionType to avoid a NullPointerException.The outcome for the user will still be an error page.
=> BAU Reverse evaluation order to avoid a NullPointerException

build.gradle
Update Verify-hub to use version 348-259, which uses `OutgoingKeySignatureTrustEngine`
=> HUB-1055-update-saml-lib-348-259

build.gradle
Update logback to 1.2.9 to mitigate CVE-2021-42550
See the article "16th of December, 2021, Release of version 1.2.9" at http://logback.qos.ch/news.html
=> BAU Update logback

.github/workflows/pre-merge-checks.yml, build.gradle
- Bump s3mock dependency to the latest version
- Bump the java version run in GA to the latest 11 version. This is to fix an error which happens when running the integration tests and is caued by the upgrade to s3mock https://github.com/adobe/S3Mock/issues/720
=> BAU - Bump s3mock dependency to the latest

Dockerfile
- So we are running on the latest java11 version and to keep it consistent with what we run in the pipeline and GH actions.
- Pulled from https://hub.docker.com/layers/amd64/openjdk/11.0.16-jre/images/sha256-762d8d035c3b1c98d30c5385f394f4d762302ba9ee8e0da8c93344c688d160b2?context=explore
=> BAU - Up the JDK11 base image that we use to 11.0.16

build.gradle, hub/config/build.gradle
- s3mock was brining in a older version of snakeYaml. We want to bring in the latest version so exclude the snakeYaml as a transitive dependency and explicitly set the version to the latest
- Bump saml libs to latest version
=> BAU - Fix the version of snakeYaml to the latest

.sdkmanrc, build.gradle
Upgrade commons-text dependency to beyond 1.9.
We can see this with:
````
❯ ./gradlew allDeps | grep "commons-text" | sort | uniq
|         \--- org.apache.commons:commons-text:1.10.0
|    |    \--- org.apache.commons:commons-text:1.10.0
|    |    |    \--- org.apache.commons:commons-text:1.10.0
|         \--- org.apache.commons:commons-text:1.10.0
|    |         \--- org.apache.commons:commons-text:1.10.0
|    |         |    \--- org.apache.commons:commons-text:1.10.0
|    |    \--- org.apache.commons:commons-text:1.10.0
|    |    |    |    \--- org.apache.commons:commons-text:1.10.0
````
=> BAU update commons-text version
